"use client";

import { useCallback, useEffect, useState } from "react";
import { ClipboardList, PackagePlus, Plus, StickyNote } from "lucide-react";
import { addStudentPrivateNote, assignStudentPackage, createStudentHomework, listStudentLearning, reviewStudentHomework, type PackageOption, type PackagePurchase, type StudentPayment } from "@/lib/admin/student-learning";
import type { Tables } from "@/types/database.types";

export type LearningSection="lessons"|"homework"|"packages"|"payments"|"notes";
export function StudentLearningManager({userId,section,onChanged}:{userId:string;section:LearningSection;onChanged?:()=>void}){
  const[lessons,setLessons]=useState<Tables<"student_lessons">[]>([]);const[homework,setHomework]=useState<Tables<"student_homework">[]>([]);const[purchases,setPurchases]=useState<PackagePurchase[]>([]);const[payments,setPayments]=useState<StudentPayment[]>([]);const[notes,setNotes]=useState<Tables<"student_admin_notes">[]>([]);const[packages,setPackages]=useState<PackageOption[]>([]);const[error,setError]=useState("");const[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const r=await listStudentLearning(userId);setLessons(r.lessons);setHomework(r.homework);setPurchases(r.purchases);setPayments(r.payments);setNotes(r.notes);setPackages(r.packages);setError(r.error||"");},[userId]);
  useEffect(()=>{void load();},[load]);
  const changed=()=>{void load();onChanged?.();};
  if(error)return <Notice tone="error">{error}</Notice>;
  if(section==="lessons")return <div className="space-y-2">{lessons.length?lessons.map((l)=><Card key={l.id}><div className="flex justify-between gap-3"><strong>{l.title}</strong><Badge>{l.status}</Badge></div><p>{l.subject} · {new Date(l.lesson_date).toLocaleString("tr-TR")} · {l.duration_minutes} dk</p>{l.teacher_note&&<p className="mt-1">Not: {l.teacher_note}</p>}</Card>):<Empty>Henüz ders kaydı yok. Randevu sekmesinden tamamlanan randevuyu ders geçmişine işleyebilirsiniz.</Empty>}</div>;
  if(section==="homework")return <HomeworkPanel homework={homework} lessons={lessons} userId={userId} busy={busy} setBusy={setBusy} setError={setError} changed={changed}/>;
  if(section==="packages")return <PackagePanel purchases={purchases} packages={packages} userId={userId} busy={busy} setBusy={setBusy} setError={setError} changed={changed}/>;
  if(section==="payments")return <div className="space-y-2">{payments.length?payments.map((p)=><Card key={p.id}><div className="flex justify-between gap-3"><strong>{money(p.amount,p.currency)}</strong><Badge>{p.status}</Badge></div><p>{p.payment_method==="bank_transfer"?"Havale / EFT":"Kart"} · {p.public_reference} · {new Date(p.created_at).toLocaleString("tr-TR")}</p></Card>):<Empty>Bu öğrenciyle bağlantılı ödeme kaydı yok.</Empty>}<p className="text-[11px] text-muted-foreground">Bekleyen manuel havaleler yalnızca Ödemeler ekranındaki açık onay işlemiyle ödendi durumuna geçer.</p></div>;
  return <NotesPanel notes={notes} busy={busy} setBusy={setBusy} setError={setError} userId={userId} changed={changed}/>;
}

function HomeworkPanel({homework,lessons,userId,busy,setBusy,setError,changed}:{homework:Tables<"student_homework">[];lessons:Tables<"student_lessons">[];userId:string;busy:boolean;setBusy:(v:boolean)=>void;setError:(v:string)=>void;changed:()=>void}){
  const[form,setForm]=useState({title:"",description:"",dueDate:"",lessonId:"",fileUrl:""});
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);const{error}=await createStudentHomework({student_user_id:userId,title:form.title.trim(),description:form.description.trim(),due_date:form.dueDate?new Date(form.dueDate).toISOString():null,lesson_id:form.lessonId||null,assignment_file_url:form.fileUrl.trim()||null});setBusy(false);if(error)setError(error.message);else{setForm({title:"",description:"",dueDate:"",lessonId:"",fileUrl:""});changed();}}
  return <div className="space-y-4"><form onSubmit={submit} className="grid gap-2 rounded-xl border border-border bg-background-soft/40 p-3"><h4 className="flex items-center gap-2 text-xs font-bold"><ClipboardList className="size-4"/>Ödev Ata</h4><Input required placeholder="Başlık" value={form.title} onChange={(v)=>setForm({...form,title:v})}/><textarea required placeholder="Açıklama" value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})} className={field}/><div className="grid gap-2 sm:grid-cols-2"><input type="datetime-local" value={form.dueDate} onChange={(e)=>setForm({...form,dueDate:e.target.value})} className={field}/><select value={form.lessonId} onChange={(e)=>setForm({...form,lessonId:e.target.value})} className={field}><option value="">Ders bağlantısı yok</option>{lessons.map((l)=><option key={l.id} value={l.id}>{l.title}</option>)}</select></div><Input placeholder="Dosya bağlantısı (isteğe bağlı)" value={form.fileUrl} onChange={(v)=>setForm({...form,fileUrl:v})}/><Submit busy={busy}>Ödevi Ata</Submit></form><div className="space-y-2">{homework.length?homework.map((h)=><HomeworkReview key={h.id} item={h} changed={changed}/>):<Empty>Henüz ödev yok.</Empty>}</div></div>;
}
function HomeworkReview({item,changed}:{item:Tables<"student_homework">;changed:()=>void}){const[feedback,setFeedback]=useState(item.teacher_feedback||"");return <Card><div className="flex justify-between gap-2"><strong>{item.title}</strong><Badge>{item.status}</Badge></div><p>{item.description}</p>{item.assignment_file_url&&<a className="text-primary underline" href={item.assignment_file_url} target="_blank" rel="noreferrer">Atama dosyası</a>}{item.submission_text&&<p className="mt-2 rounded bg-white p-2">Öğrenci yanıtı: {item.submission_text}</p>}<textarea value={feedback} onChange={(e)=>setFeedback(e.target.value)} placeholder="Geri bildirim" className={`${field} mt-2`}/><div className="mt-2 flex flex-wrap gap-2"><button onClick={async()=>{await reviewStudentHomework(item.id,"reviewed",feedback);changed();}} className="rounded border border-border px-2 py-1">İncelendi</button><button onClick={async()=>{await reviewStudentHomework(item.id,"completed",feedback);changed();}} className="rounded bg-ink px-2 py-1 text-white">Tamamlandı</button></div></Card>}

function PackagePanel({purchases,packages,userId,busy,setBusy,setError,changed}:{purchases:PackagePurchase[];packages:PackageOption[];userId:string;busy:boolean;setBusy:(v:boolean)=>void;setError:(v:string)=>void;changed:()=>void}){const today=new Date().toISOString().slice(0,10);const[form,setForm]=useState({packageId:"",startDate:today,endDate:"",lessonCount:"",price:"",currency:"TRY",paymentStatus:"pending" as "pending"|"waived"});const selected=packages.find((p)=>p.id===form.packageId);function choose(id:string){const p=packages.find((x)=>x.id===id);setForm({...form,packageId:id,lessonCount:String(p?.lesson_count||""),price:String(p?.current_total??p?.price_amount??""),currency:p?.currency||"TRY"});}async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);const r=await assignStudentPackage({studentId:userId,packageId:form.packageId,startDate:form.startDate,endDate:form.endDate||null,lessonCount:Number(form.lessonCount),priceAmount:Number(form.price),currency:form.currency,paymentStatus:form.paymentStatus});setBusy(false);if(r.error)setError(r.error);else changed();}
  return <div className="space-y-4"><form onSubmit={submit} className="grid gap-2 rounded-xl border border-border bg-background-soft/40 p-3"><h4 className="flex items-center gap-2 text-xs font-bold"><PackagePlus className="size-4"/>Manuel Paket Ata</h4><select required value={form.packageId} onChange={(e)=>choose(e.target.value)} className={field}><option value="">Paket seçin</option>{packages.map((p)=><option key={p.id} value={p.id}>{p.name_tr||p.name_en||p.id}</option>)}</select><div className="grid gap-2 sm:grid-cols-2"><input required type="date" value={form.startDate} onChange={(e)=>setForm({...form,startDate:e.target.value})} className={field}/><input type="date" min={form.startDate} value={form.endDate} onChange={(e)=>setForm({...form,endDate:e.target.value})} className={field}/><Input required type="number" placeholder="Ders sayısı" value={form.lessonCount} onChange={(v)=>setForm({...form,lessonCount:v})}/><Input required type="number" placeholder="Ücret" value={form.price} onChange={(v)=>setForm({...form,price:v})}/><Input required placeholder="Para birimi" value={form.currency} onChange={(v)=>setForm({...form,currency:v.toUpperCase()})}/><select value={form.paymentStatus} onChange={(e)=>setForm({...form,paymentStatus:e.target.value as "pending"|"waived"})} className={field}><option value="pending">Ödeme bekliyor</option><option value="waived">Ücretsiz / Muaf</option></select></div><p className="text-[10px] text-muted-foreground">Manuel atama “ödendi” olarak kaydedilemez. Havale ödemesi Ödemeler ekranında ayrıca onaylanmalıdır.</p><Submit busy={busy} disabled={!selected}>Paketi Ata</Submit></form><div className="space-y-2">{purchases.length?purchases.map((p)=><Card key={p.id}><div className="flex justify-between gap-2"><strong>{p.pricing_packages?.name_tr||p.pricing_packages?.name_en||p.package_id}</strong><Badge>{p.status}</Badge></div><p>{p.lessons_used}/{p.lesson_count} ders · {Math.max(0,p.lesson_count-p.lessons_used)} kalan · {p.payment_status}</p><p>{p.start_date}{p.end_date?` — ${p.end_date}`:""}{p.price_amount!==null?` · ${money(p.price_amount,p.currency)}`:""}</p></Card>):<Empty>Atanmış paket yok.</Empty>}</div></div>}

function NotesPanel({notes,busy,setBusy,setError,userId,changed}:{notes:Tables<"student_admin_notes">[];busy:boolean;setBusy:(v:boolean)=>void;setError:(v:string)=>void;userId:string;changed:()=>void}){const[note,setNote]=useState("");async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);const{error}=await addStudentPrivateNote(userId,note);setBusy(false);if(error)setError(error.message);else{setNote("");changed();}}return <div className="space-y-4"><form onSubmit={submit} className="space-y-2 rounded-xl border border-border p-3"><h4 className="flex items-center gap-2 text-xs font-bold"><StickyNote className="size-4"/>Özel Yönetici Notu</h4><textarea required maxLength={5000} value={note} onChange={(e)=>setNote(e.target.value)} className={field} placeholder="Bu not öğrenci tarafından görülemez."/><Submit busy={busy}>Not Ekle</Submit></form>{notes.length?notes.map((n)=><Card key={n.id}><p className="whitespace-pre-wrap text-foreground">{n.note}</p><p>{new Date(n.created_at).toLocaleString("tr-TR")}</p></Card>):<Empty>Özel not yok.</Empty>}</div>}

const field="min-h-9 w-full rounded-lg border border-input bg-white px-2 py-2 text-xs focus:border-primary focus:outline-hidden";
function Input({value,onChange,placeholder,required=false,type="text"}:{value:string;onChange:(v:string)=>void;placeholder:string;required?:boolean;type?:string}){return <input required={required} type={type} value={value} onChange={(e)=>onChange(e.target.value)} placeholder={placeholder} className={field}/>}
function Submit({busy,disabled=false,children}:{busy:boolean;disabled?:boolean;children:React.ReactNode}){return <button disabled={busy||disabled} className="inline-flex min-h-9 w-fit items-center gap-1 rounded-lg bg-ink px-3 text-xs font-semibold text-white disabled:opacity-50"><Plus className="size-3"/>{busy?"Kaydediliyor…":children}</button>}
function Card({children}:{children:React.ReactNode}){return <div className="rounded-lg border border-border bg-background-soft/50 p-3 text-xs [&_p]:mt-1 [&_p]:text-muted-foreground">{children}</div>}
function Badge({children}:{children:React.ReactNode}){return <span className="h-fit rounded-full border border-border bg-white px-2 py-0.5 text-[10px] font-semibold">{children}</span>}
function Empty({children}:{children:React.ReactNode}){return <div className="rounded-lg border border-dashed border-border p-4 text-xs text-muted-foreground">{children}</div>}
function Notice({children}:{children:React.ReactNode;tone:"error"}){return <div className="rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-800">{children}</div>}
function money(amount:number,currency:string){try{return new Intl.NumberFormat("tr-TR",{style:"currency",currency}).format(amount)}catch{return `${amount} ${currency}`}}
