import type { AboutContent } from "../about";

export const about: AboutContent = {
  metadata: {
    title: "Hakkımızda | Oriens Academy",
    description: "Oriens Academy'nin 15 uluslararası sınava yönelik birebir hazırlık, akademik ölçüm ve üniversite ders desteği yaklaşımını tanıyın.",
  },
  breadcrumb: { ariaLabel: "Sayfa yolu", home: "Ana Sayfa", current: "Hakkımızda" },
  hero: {
    eyebrow: "Hakkımızda",
    title: "Oriens Academy ile tanışın.",
    description: "Oriens Academy; 15 uluslararası sınava hazırlık ile matematik ve fizik odaklı üniversite ders desteğini, birebir ve ölçülebilir bir çalışma sistemi içinde sunar. Kurumun yaklaşımı ezbere değil, sınavın mantığını anlamaya ve öğrencinin hedefi için doğru rotayı kurmaya dayanır.",
    primaryCta: "Ücretsiz Tanışma Görüşmesi",
    secondaryCta: "Sınavları İncele",
    visualLabel: "Tutor Doğuhan — Matematik-Fizik Eğitmeni",
    visualSteps: [
      "Robert Kolej",
      "St. Joseph",
      "Liceo Italiano",
      "Üsküdar Amerikan Lisesi",
      "Galatasaray Lisesi",
      "Saint Benoit Fransız Lisesi",
      "Notre Dame de Sion",
      "İstanbul Alman Lisesi",
      "Avusturya Lisesi",
    ],
  },
  story: {
    eyebrow: "Yaklaşımımız",
    title: "Ezber değil, sınavın mantığını çözmek üzerine kurulu bir çalışma sistemi.",
    paragraphs: [
      "10 yılı aşkın süredir uluslararası müfredatlarda eğitim gören öğrencilerle birebir çalışıyoruz. Robert Kolej, St. Joseph, Liceo Italiano, Üsküdar Amerikan Lisesi, Galatasaray Lisesi, Saint Benoit Fransız Lisesi, Notre Dame de Sion, İstanbul Alman Lisesi ve Avusturya Lisesi gibi köklü okulların öğrencilerinin akademik hedeflerine ulaşmalarına destek veriyoruz.",
      "Her sınavın kendi dili, puanlama mantığı ve zaman baskısı olduğu için hazırlık sürecini doğrudan o sınava özel kurguluyoruz.",
    ],
    note: "Doğuhan — Matematik-Fizik Eğitmeni & Oriens Academy Kurucusu",
  },
  principles: {
    eyebrow: "İlkeler",
    title: "Başarıyı getiren temel prensiplerimiz.",
    intro: "Her ders ve hazırlık süreci bu beş temel ilkeye dayanır.",
    items: [
      { id: "direction", title: "Sınavın Mantığı", description: "Ezbere değil, sorunun arkasındaki mantığı anlamaya odaklanıyoruz." },
      { id: "individualisation", title: "Birebir Çalışma", description: "Öğrencinin seviyesine, hızına ve eksiklerine özel kurgulanan ders akışı." },
      { id: "clarity", title: "Ölçülebilir İlerleme", description: "Düzenli zamanlı deneme sınavları ve net durum analizleri." },
      { id: "review", title: "Zaman Yönetimi", description: "Sınav anındaki zaman baskısını yönetme teknikleri ve stratejileri." },
      { id: "integrity", title: "Akademik Güven", description: "10+ yıllık deneyim ile üniversiteye giden yolda sağlam bir rehberlik." },
    ],
  },
  team: {
    eyebrow: "Uzman Kadro",
    title: "Kurucu eğitmenimiz",
    intro: "Alanında uzman eğitim kadrosu.",
    members: [
      {
        id: "doguhan",
        name: "Doğuhan",
        role: "Matematik-Fizik Eğitmeni / Kurucu",
        bio: "Matematik-Fizik eğitmeni. 10 yılı aşkın süredir IB, AP, A-Level, SAT, ESAT, TMUA, MAT, STEP, PAT, TARA ve IGCSE öğrencileriyle birebir çalışıyor; aralarında Robert Kolej, St. Joseph, Liceo Italiano, Üsküdar Amerikan, Galatasaray Lisesi, Saint Benoit Fransız Lisesi, Notre Dame de Sion, İstanbul Alman Lisesi ve Avusturya Lisesi gibi yabancı müfredat okullarının öğrencileri de var. Yaklaşım; ezber değil, sınavın mantığını çözmek üzerine kurulu.",
        credentials: [
          "Robert Kolej",
          "St. Joseph",
          "Liceo Italiano",
          "Üsküdar Amerikan Lisesi",
          "Galatasaray Lisesi",
          "Saint Benoit Fransız Lisesi",
          "Notre Dame de Sion",
          "İstanbul Alman Lisesi",
          "Avusturya Lisesi",
        ],
      },
    ],
    fallbackTitle: "Birebir Eğitmen Desteği",
    fallbackBody: "Tüm dersler doğrudan kurucu eğitmenimiz Doğuhan rehberliğinde yürütülmektedir.",
    fallbackPoints: ["10+ Yıl Deneyim", "Hedef Okullar & Yabancı Müfredatlar", "Birebir Ders Kurgusu"],
  },
  brandMoment: {
    eyebrow: "ORIENS Academy",
    title: "Rotanı birlikte çizelim.",
    body: "Hedefinizdeki üniversite ve sınava yönelik en doğru çalışma rotasını oluşturuyoruz.",
    steps: ["Analiz", "Strateji", "Pratik", "Başarı"],
  },
  outcomes: {
    eyebrow: "Okullarımız",
    title: "Birlikte çalıştığımız öğrenci grupları.",
    intro: "Kurucumuzun 10 yılı aşkın eğitmenlik geçmişinde bu okullarda öğrenim gören öğrencilerle birebir çalışmalar yer almaktadır.",
    metrics: [],
    items: [
      { title: "Robert Kolej", description: "IB ve AP sınavlarında hedefli ders desteği." },
      { title: "St. Joseph", description: "Fransız/uluslararası müfredat matematik ve fizik desteği." },
      { title: "Liceo Italiano", description: "İtalyan Lisesi ve IMAT / uluslararası sınav hazırlığı." },
      { title: "Üsküdar Amerikan Lisesi", description: "IB HL/SL derslerinde ve SAT süreçlerinde birebir takviye." },
      { title: "Galatasaray Lisesi", description: "Fransız Bakaloryası ve uluslararası sınav desteği." },
      { title: "Saint Benoit Fransız Lisesi", description: "Fransız müfredatı matematik ve fen dersleri takviyesi." },
      { title: "Notre Dame de Sion", description: "İleri düzey matematik ve fizik sınav hazırlığı." },
      { title: "İstanbul Alman Lisesi", description: "Abitur ve uluslararası STEM kabul sınavları hazırlığı." },
      { title: "Avusturya Lisesi", description: "Matura ve ileri düzey matematik-fizik özel ders desteği." },
    ],
    disclaimer: "Tüm okul isimleri öğrencilerimizin eğitim gördüğü kurumları ifade etmektedir; resmi iş birliği veya kurum onayı anlamına gelmez.",
  },
  trust: {
    eyebrow: "İletişim Kanalları",
    title: "Bize ulaşın.",
    intro: "Sorularınız ve randevu talepleriniz için doğrudan iletişim kanallarımız:",
    examLabel: "İletişim",
    links: [
      { route: "contact", title: "WhatsApp", description: "+90 544 293 90 40 üzerinden anında mesaj gönderin.", linkLabel: "WhatsApp'tan Yazın" },
      { route: "contact", title: "Telefon", description: "0850 304 04 67 destek hattımızdan bize ulaşın.", linkLabel: "Hemen Arayın" },
      { route: "contact", title: "E-Posta", description: "info@oriens-academy.com adresinden detaylı bilgi alın.", linkLabel: "E-Posta Gönderin" },
      { route: "contact", title: "Instagram", description: "@oriens.academy hesabımızı takip edin.", linkLabel: "Instagram'da Görün" },
    ],
  },
  testimonials: {
    eyebrow: "Öğrenciler Ne Diyor",
    title: "Öğrencilerimiz Ne Diyor?",
    items: [
      {
        id: "1",
        quote: "Oğlumun IB Fizik notu belirgin şekilde yükseldi, derse artık severek katılıyor.",
        author: "Ahu G.",
        role: "Veli · IB Fizik",
      },
      {
        id: "2",
        quote: "Oğlumun IB HL Matematik ve Fizik'te motivasyonu ve özgüveni belirgin biçimde arttı.",
        author: "Yasemin T.",
        role: "Veli · IB HL Matematik & Fizik",
      },
      {
        id: "3",
        quote: "Karmaşık konuları basit anlatımıyla öğretti; tüm matematik ve fizik sınavlarımı yüksek notla geçtim.",
        author: "Ahmet S.",
        role: "Öğrenci · Üniversite Fizik",
      },
      {
        id: "4",
        quote: "Kısa sürede belirgin bir başarı sağladı, oldukça yetkin bir eğitimci.",
        author: "Ece A.",
        role: "Öğrenci · AYT Sınav Hazırlık",
      },
      {
        id: "5",
        quote: "Geometriye karşı çekingenliğimi kısa sürede aştırdı, konuları sevdirerek ve pratik ipuçlarıyla öğretti.",
        author: "Ada Elif A.",
        role: "Öğrenci · Lise Matematik & Fizik",
      },
      {
        id: "6",
        quote: "Kızımızın eksiklerini hızla tespit edip yazılı sınavına başarıyla hazırladı.",
        author: "Bülent I.",
        role: "Veli",
      },
    ],
  },
  cta: {
    eyebrow: "Tanışma Görüşmesi",
    title: "Başlamaya hazır mısınız?",
    body: "Formu doldurun veya bizimle iletişime geçin. İlk görüşme ücretsizdir.",
    primary: "Ücretsiz Tanışma Görüşmesi",
    secondary: "İletişime Geç",
  },
};
