import type { ExamDetailTextMap } from "../exams";

export const examDetailText: ExamDetailTextMap = {
  IB: {
    seoTitle: "IB Hazırlık ve Akademik Destek | Oriens Academy",
    seoDescription: "IB Diploma Programme dersleri, iç değerlendirmeler ve sınavlar için kişiselleştirilmiş akademik destek ve çalışma planlaması.",
    overview: [
      "International Baccalaureate Diploma Programme, farklı akademik alanları DP çekirdeğiyle bir araya getiren bütünlüklü bir lise programıdır.",
      "Hazırlık yalnızca final sınavlarına değil; ders seçimi, kavramsal derinlik, iç değerlendirmeler ve uzun dönemli çalışma düzenine birlikte bakmayı gerektirir.",
    ],
    preparationAreas: [
      { title: "Ders temeli", description: "Matematik ve fen derslerinde eksik kavramları belirleyip HL veya SL kapsamına uygun biçimde tamamlarız." },
      { title: "Değerlendirme dili", description: "Soru yönergelerini, çözüm sunumunu ve markscheme beklentilerini sistemli çalışırız." },
      { title: "IA planlaması", description: "Araştırma sorusu, yöntem ve akademik anlatım süreçlerinde etik sınırlar içinde rehberlik sağlarız." },
    ],
    oriensSupport: "Ders bazlı özel çalışmayı dönem planı, değerlendirme takvimi ve düzenli ilerleme takibiyle birleştiriyoruz. Öğrencinin okul programı ve seçtiği ders düzeyleri hazırlık rotasının temelini oluşturur.",
    featuredFacts: [{ label: "Program yapısı", value: "Ders grupları ve DP çekirdeği" }, { label: "Hazırlık odağı", value: "Dersler, değerlendirmeler ve akademik planlama" }],
    faqs: [
      { question: "IB desteği yalnızca final sınavlarına mı yöneliktir?", answer: "Hayır. Ders içeriği, iç değerlendirmeler, çalışma düzeni ve sınav hazırlığı öğrencinin ihtiyacına göre birlikte ele alınabilir." },
      { question: "HL ve SL öğrencileri için plan farklılaşır mı?", answer: "Evet. Ders düzeyi, okulun ilerleme sırası ve öğrencinin hedefleri çalışma kapsamını doğrudan belirler." },
      { question: "IA çalışmasında nasıl destek verilir?", answer: "Konu netleştirme, yöntem, yapı ve geri bildirim sağlanır; öğrencinin özgün çalışması korunur ve çalışma onun yerine yazılmaz." },
    ],
    cta: { title: "IB hazırlık rotanızı birlikte planlayalım.", body: "Derslerinizi, yaklaşan değerlendirmeleri ve hedeflerinizi konuşarak sürdürülebilir bir akademik plan oluşturalım.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  AP: {
    seoTitle: "AP Hazırlık ve Özel Ders | Oriens Academy",
    seoDescription: "AP Calculus, Statistics, Physics ve Chemistry dersleri için konu odaklı hazırlık, soru pratiği ve birebir akademik destek.",
    overview: ["Advanced Placement, lise öğrencilerinin üniversite düzeyindeki belirli dersleri ve bunlara bağlı değerlendirmeleri takip edebildiği konu bazlı bir programdır.", "Her AP dersinin kapsamı ve değerlendirme biçimi farklıdır; bu nedenle hazırlık seçilen dersin resmî çerçevesi üzerinden kurulmalıdır."],
    preparationAreas: [
      { title: "Konu haritası", description: "Seçilen AP dersinin ünitelerini mevcut bilgi düzeyiyle eşleştiririz." },
      { title: "Soru türleri", description: "Çoktan seçmeli, serbest yanıt veya derse özgü görevler için uygun çözüm yaklaşımı geliştiririz." },
      { title: "Deneme analizi", description: "Yanlışları konu, yorum ve zaman yönetimi boyutlarında sınıflandırırız." },
    ],
    oriensSupport: "Oriens desteği seçilen AP dersine göre özelleşir. Konu anlatımı, kontrollü soru pratiği ve geri bildirim döngüsü öğrencinin okul temposuyla birlikte planlanır.",
    featuredFacts: [{ label: "Yapı", value: "Ders ve sınav bazlı" }, { label: "Oriens odağı", value: "Matematik ve fen derslerinde derinleşme" }],
    faqs: [
      { question: "Her AP dersi için aynı hazırlık planı kullanılabilir mi?", answer: "Hayır. Ders kapsamı ve değerlendirme biçimi değiştiği için plan seçilen AP dersine göre hazırlanır." },
      { question: "AP sonucu üniversite kredisi sağlar mı?", answer: "Kredi ve yerleştirme politikaları kuruma göre değişir. Hedef üniversitenin güncel politikasını doğrudan kontrol etmek gerekir." },
      { question: "Hazırlığa ne zaman başlanmalı?", answer: "Başlangıç zamanı öğrencinin konu temeline, okul programına ve hedeflediği derslere göre belirlenmelidir." },
    ],
    cta: { title: "AP dersiniz için net bir çalışma sistemi kuralım.", body: "Seçtiğiniz AP dersini ve mevcut seviyenizi değerlendirerek konu ve soru pratiği rotasını belirleyelim.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  IGCSE: {
    seoTitle: "IGCSE Hazırlık ve Ders Desteği | Oriens Academy",
    seoDescription: "Cambridge IGCSE matematik ve fen derslerinde müfredat takibi, kavram tekrarı ve sınav odaklı birebir akademik destek.",
    overview: ["Cambridge IGCSE, okulların farklı ders kombinasyonları oluşturabildiği uluslararası bir ortaöğretim programı ve yeterlilik sistemidir.", "Değerlendirme biçimi derse göre değişebildiğinden hazırlık, öğrencinin kesin ders kodu ve güncel müfredat belgesi üzerinden yürütülmelidir."],
    preparationAreas: [
      { title: "Syllabus takibi", description: "Ders koduna ait güncel kapsamı okul ilerleyişiyle eşleştiririz." },
      { title: "Kavramsal temel", description: "Matematik ve fen konularında ezber yerine neden-sonuç ilişkisini güçlendiririz." },
      { title: "Sınav uygulaması", description: "Geçmiş sorular ve değerlendirme dili üzerinden cevap kalitesini geliştiririz." },
    ],
    oriensSupport: "Öğrencinin aldığı IGCSE dersini ve okul takvimini temel alan düzenli destek sağlıyoruz. Konu anlatımı, ödev yaklaşımı ve sınav pratiği aynı ilerleme planında buluşur.",
    featuredFacts: [{ label: "Program yaklaşımı", value: "Esnek ders kombinasyonları" }, { label: "Oriens kapsamı", value: "Matematik ve fen ders desteği" }],
    faqs: [
      { question: "Tüm IGCSE derslerinin sınav yapısı aynı mıdır?", answer: "Hayır. Yazılı, sözlü, ders içi çalışma veya uygulamalı değerlendirmeler derse göre değişebilir; doğru müfredat kontrol edilmelidir." },
      { question: "Core ve Extended kapsamı hazırlığı etkiler mi?", answer: "Evet. İlgili derste seçenek bulunuyorsa öğrencinin takip ettiği kapsam çalışma planını belirler." },
      { question: "Okul dersleriyle paralel destek alınabilir mi?", answer: "Evet. Plan okulun konu sırası ve yaklaşan değerlendirmeleriyle uyumlu kurulabilir." },
    ],
    cta: { title: "IGCSE derslerinizi sağlam bir temele oturtalım.", body: "Ders kodlarınızı ve okul planınızı inceleyerek düzenli, konu odaklı bir destek rotası oluşturalım.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  "A-Level": {
    seoTitle: "A-Level Hazırlık ve Özel Ders | Oriens Academy",
    seoDescription: "Cambridge, Edexcel ve OxfordAQA A-Level matematik, fen ve ileri modüller için derinlemesine akademik destek.",
    overview: [
      "GCE Advanced Level (A-Level), Birleşik Krallık başta olmak üzere dünya çapındaki seçkin üniversitelerin lisans kabulünde temel aldığı konu odaklı ileri ortaöğretim yeterliliğidir.",
      "Öğrencilerin derinlemesine uzmanlaşmasını gerektiren bu programda, kavramsal kavrayış ile sınav kâğıdı çözüm tekniği birlikte geliştirilmelidir.",
    ],
    preparationAreas: [
      { title: "Derinlemesine Konu Hâkimiyeti", description: "Pure Math, Mechanics, Statistics, Fizik ve Kimya ünitelerini sıfırdan ve eksiksiz kavratırız." },
      { title: "Soru Türleri ve Mark Scheme", description: "Sınav kurullarının resmi puanlama anahtarlarına ve gösterim standartlarına uygun çözüm disiplini kazandırırız." },
      { title: "Zamanlı Deneme ve Hata Analizi", description: "Zaman baskısı altında hatasız işlem yapma ve adım adım tam puan alma becerisini geliştiririz." },
    ],
    oriensSupport: "Öğrencinin kayıtlı olduğu sınav kuruluna (Cambridge CAIE, Edexcel Pearson, OxfordAQA) özel modüler çalışma planı uygularız. A* hedefi için gereken problem çözme stratejilerini sistematik aktarırız.",
    featuredFacts: [{ label: "Sınav Kurulları", value: "Cambridge, Pearson Edexcel, OxfordAQA" }, { label: "Oriens Hedefi", value: "A* ve A derecesi odaklı hazırlık" }],
    faqs: [
      { question: "A-Level hazırlığı okul ile eşzamanlı yürütülebilir mi?", answer: "Evet. Okulunuzun müfredat takvimine paralel konu kapatma ve sınav dönemi öncesi yoğun geçmiş yıl soru kampları yapılır." },
      { question: "Farklı sınav kurulları arasında içerik farkı var mıdır?", answer: "Evet. Cambridge, Edexcel ve AQA arasında soru formatı ve formül kâğıdı kullanımı farklılıkları bulunur; çalışma doğrudan ilgili kurulun spesifikasyonuna göre yapılır." },
    ],
    cta: { title: "A-Level hedefinizi A* seviyesine taşıyalım.", body: "Mevcut derslerinizi ve hedef üniversitenizi değerlendirerek size özel bir A-Level çalışma rotası kuralım.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  SAT: {
    seoTitle: "Digital SAT Hazırlık ve Özel Ders | Oriens Academy",
    seoDescription: "Digital SAT Reading and Writing ile Math alanları için kişiselleştirilmiş hazırlık, deneme analizi ve birebir akademik destek.",
    overview: ["Digital SAT, okuma-yazma ve matematik becerilerini ölçen adaptif bir sınavdır ve başta ABD olmak üzere dünya üniversitelerinde kullanılır.", "Modül bazlı adaptif yapı, öğrencinin sınav anındaki stratejik doğruluğunu ve zaman yönetimini doğrudan belirler."],
    preparationAreas: [
      { title: "Reading & Writing", description: "Kısa metinlerde kanıt, bağlam, dil bilgisi ve anlatım kararlarını birlikte çalışırız." },
      { title: "Matematik", description: "Cebir, problem çözme, veri analizi ve ileri matematik konularında kavram-uygulama bağını güçlendiririz." },
      { title: "Dijital sınav stratejisi", description: "Modül düzeni, Desmos kullanımı ve deneme sonrası hata analizi için tekrar edilebilir bir sistem kurarız." },
    ],
    oriensSupport: "Başlangıç değerlendirmesinden sonra konu eksikleri, soru yaklaşımı ve deneme performansı tek planda birleştirilir. İlerleme, yalnızca toplam sonuçla değil hata türleri ve çözüm kalitesiyle izlenir.",
    featuredFacts: [{ label: "Değerlendirme alanları", value: "Reading & Writing · Math" }, { label: "Hazırlık modeli", value: "Teşhis · çalışma · deneme analizi" }],
    faqs: [
      { question: "SAT hangi öğrenciler için anlamlıdır?", answer: "SAT isteyen, kabul eden veya başvurusunda sınav sonucu kullanmayı değerlendiren lisans adayları için anlamlı olabilir. Hedef kurum politikaları kontrol edilmelidir." },
      { question: "SAT hazırlığı yalnızca deneme çözmekten mi oluşur?", answer: "Hayır. Denemeler teşhis aracıdır; kalıcı gelişim için konu temeli, soru çözümü ve yanlış analizi birlikte yürütülür." },
      { question: "Oriens birebir SAT desteği sağlar mı?", answer: "Evet. Çalışma kapsamı öğrencinin mevcut seviyesi, hedefi ve müsait zamanına göre kişiselleştirilebilir." },
    ],
    cta: { title: "SAT hazırlık sürecinizi birlikte planlayalım.", body: "Mevcut seviyenizi ve başvuru hedeflerinizi konuşarak ölçülebilir bir çalışma rotası oluşturalım.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  ACT: {
    seoTitle: "ACT Hazırlık ve Özel Ders | Oriens Academy",
    seoDescription: "ACT English, Math, Reading ve Science bölümleri için hız, doğruluk ve strateji odaklı birebir hazırlık.",
    overview: [
      "American College Testing (ACT), ABD ve dünya genelindeki üniversitelere lisans başvurularında kullanılan standart bir kabul sınavıdır.",
      "Özellikle Fen Okuryazarlığı (Science Reasoning) ve yüksek tempolu soru çözme hızı gerektiren yapısıyla SAT'tan ayrışır.",
    ],
    preparationAreas: [
      { title: "Science Reasoning", description: "Grafik, tablo ve deney kurgularını saniyeler içinde analiz edip bilimsel mantık yürütmeyi çalışırız." },
      { title: "Math & Geometry", description: "Geniş konu yelpazesindeki matematik sorularını hızlı ve işlem hatasız çözmeyi pratik ederiz." },
      { title: "Zaman ve Hız Yönetimi", description: "Bölüm başına düşen dar süreyi en yüksek netle tamamlamak için tempo ve soru eleme teknikleri uygularız." },
    ],
    oriensSupport: "Öğrencinin güçlü olduğu alanları korurken, fen ve hızlı okuma bölümlerindeki eksikleri hedefli soru setleri ve simülasyon denemeleriyle kapatıyoruz.",
    featuredFacts: [{ label: "Puan Skalası", value: "1–36 Kompozit Puan" }, { label: "Bölümler", value: "English, Math, Reading, Science (+Writing)" }],
    faqs: [
      { question: "SAT mi ACT mi seçmeliyim?", answer: "Teşhis denemesi sonucunda öğrencinin hız, fen okuryazarlığı ve matematik yapısına göre en avantajlı sınav belirlenir." },
      { question: "Science bölümü fen bilgisi ezberi gerektirir mi?", answer: "Science bölümü genel fen bilgisinden ziyade verilen veri, grafik ve çelişen hipotezleri hızlı yorumlama becerisini ölçer." },
    ],
    cta: { title: "ACT sınavında hedef puanınıza ulaşın.", body: "Seviyenizi test edelim ve ACT temponuza uygun birebir çalışma takviminizi oluşturalım.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  ESAT: {
    seoTitle: "ESAT Hazırlık ve Akademik Destek | Oriens Academy",
    seoDescription: "ESAT matematik ve fen modülleri için ders temeli, uygulamalı problem çözme ve sınav odaklı birebir hazırlık.",
    overview: ["Engineering and Science Admissions Test, seçili mühendislik ve fen programlarının başvurularında kullanılabilen modüler bir kabul sınavıdır.", "Adayın çalışması gereken modüller başvurduğu programa göre değişebildiği için hazırlık öncesinde üniversitenin güncel ders sayfası kontrol edilmelidir."],
    preparationAreas: [
      { title: "Zorunlu matematik temeli", description: "Matematik bilgisini yeni durumlarda uygulama ve kısa çözüm yolu geliştirme üzerine çalışırız." },
      { title: "Programa uygun modüller", description: "Fizik, kimya, biyoloji veya ileri matematik çalışmasını gerçek başvuru gerekliliğine göre seçeriz." },
      { title: "Teknik problem çözme", description: "Bilgiyi tanımaktan öte, verilen koşullara hızlı ve kontrollü biçimde uygulamayı geliştiririz." },
    ],
    oriensSupport: "Önce hedef programın istediği modülleri netleştirir, ardından konu kontrol listesi ve zamanlı problem çözme pratiği oluştururuz. Hazırlık, resmî spesifikasyonla uyumlu tutulur.",
    featuredFacts: [{ label: "Sınav yaklaşımı", value: "Matematik ve fen bilgisini uygulama" }, { label: "Modül seçimi", value: "Hedef programa göre değişir" }],
    faqs: [
      { question: "Hangi ESAT modüllerine hazırlanmalıyım?", answer: "Bu, başvurduğunuz programa bağlıdır. Üniversitenin güncel program sayfasındaki gereklilikler esas alınmalıdır." },
      { question: "ESAT hazırlığında okul bilgisi yeterli midir?", answer: "Resmî sınav mevcut okul bilgisini uygulamaya odaklanır; yine de eksik konu ve yeni problem türleri için hedefli pratik gerekir." },
      { question: "Oriens fen ve matematik modüllerini birlikte planlar mı?", answer: "Evet. İstenen modül kombinasyonuna göre dersler tek bir hazırlık takviminde koordine edilebilir." },
    ],
    cta: { title: "ESAT modül rotanızı netleştirelim.", body: "Hedef programınızı ve ders temelinizi değerlendirerek doğru modüllere odaklanan bir hazırlık planı kuralım.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  TMUA: {
    seoTitle: "TMUA Hazırlık ve Matematik Özel Ders | Oriens Academy",
    seoDescription: "TMUA matematiksel bilgi uygulaması, akıl yürütme ve mantık alanları için birebir hazırlık ve problem çözme desteği.",
    overview: ["Test of Mathematics for University Admission, matematik veya matematik yoğun programlara başvuran adayların matematik bilgisini yeni durumlarda kullanma ve akıl yürütme becerisini değerlendirmek için kullanılır.", "TMUA gerekliliği ve sonucun kullanım biçimi kurum ve programa göre değişebilir; güncel koşullar resmî üniversite sayfasından doğrulanmalıdır."],
    preparationAreas: [
      { title: "Bilgiyi uygulama", description: "Standart konuları alışılmadık soru bağlamlarında esnek biçimde kullanmayı geliştiririz." },
      { title: "Matematiksel akıl yürütme", description: "Önermeler, gereklilik-yeterlilik ve mantıksal çıkarım üzerinde çalışırız." },
      { title: "Çözüm verimliliği", description: "Alternatif yolları karşılaştırıp kontrollü ve ekonomik çözüm seçmeyi pratik ederiz." },
    ],
    oriensSupport: "Konu tekrarını, matematiksel muhakeme ve zamanlı soru setleriyle birleştiriyoruz. Yanlışlar yalnızca sonuç üzerinden değil, kullanılan varsayım ve çözüm yolu üzerinden incelenir.",
    featuredFacts: [{ label: "Ana eksen", value: "Matematiksel uygulama ve akıl yürütme" }, { label: "İlgili programlar", value: "Matematik yoğun lisans alanları" }],
    faqs: [
      { question: "TMUA ileri matematik bilgisi mi, akıl yürütme mi ölçer?", answer: "Sınav belirlenmiş matematik içeriğini yeni durumlara uygulama ve matematiksel akıl yürütme becerisine odaklanır; ikisi birlikte çalışılmalıdır." },
      { question: "TMUA için yalnızca konu tekrarı yeterli midir?", answer: "Genellikle hayır. Konu hâkimiyetinin yanında mantık dili, yeni problem türleri ve zamanlı uygulama gerekir." },
      { question: "Hedef üniversitem TMUA istiyor mu?", answer: "Gereklilikler değişebilir. Başvuru döneminde üniversitenizin ilgili program sayfasını kontrol edin." },
    ],
    cta: { title: "TMUA matematik rotanızı birlikte çizelim.", body: "Konu temeliniz ve problem çözme yaklaşımınız üzerinden kişiselleştirilmiş bir çalışma sistemi oluşturalım.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  TARA: {
    seoTitle: "Mimarlık Kabul Sınavı (TARA / TEST-ARCHED) Hazırlığı | Oriens Academy",
    seoDescription: "Politecnico di Milano, Torino ve uluslararası mimarlık lisans kabulleri için mekânsal düşünme, teknik çizim ve geometri hazırlığı.",
    overview: [
      "Test di Ammissione ad Architettura (TEST-ARCHED / TARA), İtalya'daki tek döngülü Mimarlık fakülteleri ve uluslararası mimarlık okullarının kabulünde uygulanan merkezi sınavdır.",
      "Sınav; üç boyutlu uzamsal algı, aksonometrik/ortografik izdüşüm, fiziksel statik ilkeleri, genel kültür ve mimarlık tarihi bilgisini ölçer.",
    ],
    preparationAreas: [
      { title: "Mekânsal Akıl Yürütme ve 3D Algı", description: "Katı cisim açılımları, kesit alma, perspektif ve izdüşüm sorularında hızlı ve doğru görselleştirme çalışırız." },
      { title: "Fizik ve Yapı Statiği", description: "Kuvvet dengesi, taşıyıcı sistem mantığı ve temel fizik ilkelerinin mimarlık bağlamındaki uygulamalarını kavratırız." },
      { title: "Mimarlık ve Sanat Tarihi", description: "Antik çağdan modern döneme önemli yapılar, mimarlar, akımlar ve üslup analizleri üzerine odaklanırız." },
    ],
    oriensSupport: "Görsel ve teknik analizi matematiksel problem çözme disipliniyle harmanlayarak Politecnico di Milano ve Torino kabul barajlarını aşmanızı sağlıyoruz.",
    featuredFacts: [{ label: "Resmi Sağlayıcı", value: "CISIA / İtalya Üniversite Bakanlığı (MUR)" }, { label: "Temel Alanlar", value: "Mekânsal Akıl Yürütme, Matematik, Fizik, Sanat Tarihi" }],
    faqs: [
      { question: "Sınav İngilizce mi İtalyanca mı uygulanır?", answer: "İtalya'da İngilizce eğitim veren mimarlık programları için İngilizce (TEST-ARCHED in English), İtalyanca programlar için İtalyanca uygulanır." },
      { question: "Çizim yeteneği gerekir mi?", answer: "Sınav çoktan seçmeli formatta mekânsal ve teknik anlama becerisini ölçer; serbest el çizim yapılmaz ancak çizim mantığını okumak şarttır." },
    ],
    cta: { title: "Mimarlık fakültesi hedefinizi gerçeğe dönüştürün.", body: "Mekânsal düşünme ve teknik hazırlık sürecinizi uzman eğitmenlerimizle planlayın.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  UCAT: {
    seoTitle: "UCAT Hazırlık ve Tıp Kabul Eğitimi | Oriens Academy",
    seoDescription: "Birleşik Krallık ve Avustralya tıp fakülteleri için UCAT Verbal, Decision Making, Quantitative, Abstract Reasoning ve SJT hazırlığı.",
    overview: [
      "University Clinical Aptitude Test (UCAT - eski adıyla UKCAT), Birleşik Krallık ve Avustralya'daki seçkin tıp ve diş hekimliği fakültelerinin temel kabul sınavıdır.",
      "Yoğun zaman kısıtı altında yüksek bilişsel kapasite, veri yorumlama, örüntü tanıma ve mesleki etik muhakeme yeteneğini değerlendirir.",
    ],
    preparationAreas: [
      { title: "Verbal & Quantitative Reasoning", description: "Uzun metinleri ve sayısal verileri saniyeler içinde analiz edip doğru yargıya varma tekniği kazandırırız." },
      { title: "Decision Making & Abstract Reasoning", description: "Karmaşık mantıksal önermeleri ve soyut geometrik örüntüleri sistematik yöntemlerle çözeriz." },
      { title: "Situational Judgement (SJT)", description: "GMC (General Medical Council) etik prensiplerine tam uyumlu klinik vaka değerlendirme refleksi oluştururuz." },
    ],
    oriensSupport: "Her bir alt test için özelleştirilmiş stratejiler, klavye kısayolları kullanımı, zaman yönetimi ve Band 1 odaklı durumsal yargı analizi sağlıyoruz.",
    featuredFacts: [{ label: "Puanlama", value: "Bilişsel: 1200–3600 | SJT: Band 1–4" }, { label: "Kullanım Alanı", value: "UK, Avustralya, Yeni Zelanda Tıp ve Diş Hekimliği" }],
    faqs: [
      { question: "UCAT hazırlığına ne zaman başlanmalı?", answer: "Sınav yaz aylarında uygulandığı için en az 8-12 hafta önceden düzenli strateji ve deneme pratiği önerilir." },
      { question: "Eski adı UKCAT olan sınav ile farkı var mıdır?", answer: "Sınav 2019'da uluslararası konsorsiyuma genişleyerek UCAT adını almıştır; içerik ve format UCAT standartlarındadır." },
    ],
    cta: { title: "UCAT'ta yüksek percentile dilimini hedefleyin.", body: "Bilişsel becerilerinizi ve hızınızı test ederek tıp fakültesi yol haritanızı oluşturalım.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  LNAT: {
    seoTitle: "LNAT Hazırlık ve Hukuk Kabul Danışmanlığı | Oriens Academy",
    seoDescription: "Oxford, Cambridge, UCL, LSE ve KCL hukuk lisans başvuruları için LNAT çoktan seçmeli analitik okuma ve deneme yazımı hazırlığı.",
    overview: [
      "National Admissions Test for Law (LNAT), Birleşik Krallık'taki önde gelen hukuk fakültelerine kabulde kullanılan bağımsız düşünme ve analitik yetenek sınavıdır.",
      "Adayın hukuki bilgisi değil; karmaşık argümanları çözümleme, mantık hatalarını teşhis etme ve ikna edici akademik makale yazma yeteneği ölçülür.",
    ],
    preparationAreas: [
      { title: "Eleştirel Okuma ve Metin Analizi", description: "Felsefi, sosyolojik ve hukuki pasajlarda örtük varsayımları ve mantıksal bağları saptamayı çalışırız." },
      { title: "Mantıksal Çıkarım ve Argümantasyon", description: "Çoktan seçmeli bölümde seçenekler arasındaki ince çeldiricileri eleme yöntemlerini uygularız." },
      { title: "LNAT Essay (Akademik Deneme Yazımı)", description: "Verilen tartışmalı konularda dengeli, kanıta dayalı ve ikna edici yapılandırılmış makale yazımı geliştiririz." },
    ],
    oriensSupport: "Öğrencinin analitik düşünme derinliğini artırırken, her bir yazılan denemeye Oxford/Cambridge kabul standartlarında ayrıntılı geri bildirim sunuyoruz.",
    featuredFacts: [{ label: "Sınav Yapısı", value: "Bölüm A: 42 Çoktan Seçmeli | Bölüm B: 1 Essay" }, { label: "Hedef Okullar", value: "Oxford, Cambridge, UCL, LSE, King's College, Bristol" }],
    faqs: [
      { question: "LNAT için hukuk bilgisi gerekli midir?", answer: "Hayır. Sınav önceden hukuk bilgisi gerektirmez; tamamen eleştirel düşünme ve İngilizce yazılı ifade yeteneğine odaklanır." },
      { question: "Essay bölümü nasıl değerlendirilir?", answer: "Essay kısmı LNAT tarafından değil, başvurduğunuz üniversitenin kabul komisyonu tarafından doğrudan okunup puanlanır." },
    ],
    cta: { title: "Seçkin hukuk fakültelerine kabul kapısını aralayın.", body: "LNAT analitik okuma ve deneme yazım seviyenizi uzman eğitmenlerimizle değerlendirin.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  IMAT: {
    seoTitle: "IMAT Hazırlık ve İtalya Tıp Eğitimi | Oriens Academy",
    seoDescription: "İtalya'daki devlet üniversitelerinde İngilizce tıp eğitimi için IMAT biyoloji, kimya, fizik, matematik ve mantık hazırlığı.",
    overview: ["International Medical Admissions Test (IMAT), İtalya'daki devlet üniversitelerinde İngilizce tıp ve cerrahi lisans programlarına kabulde kullanılan ulusal seçme sınavıdır.", "Geniş fen müfredatı ve negatif puanlama sistemi, sınavda yüksek net yapmayı ve doğru soru stratejisini zorunlu kılar."],
    preparationAreas: [
      { title: "Biyoloji ve Kimya Derinliği", description: "Hücre biyolojisi, genetik, organik kimya ve biyokimya konularını IMAT soru tarzıyla eksiksiz kapatırız." },
      { title: "Fizik ve Matematik", description: "İşlem hatasız ve hızlı formül uygulamalarıyla sayısal bölümün tam nete yakın tamamlanmasını sağlarız." },
      { title: "Mantıksal Akıl Yürütme", description: "Kritik düşünme ve problem çözme sorularında zaman kazandıran eleme taktikleri geliştiririz." },
    ],
    oriensSupport: "Konu anlatımını geçmiş yıl soru çözümleri ve negatif puan yönetim simülasyonlarıyla destekleyerek Milano, Roma, Bologna gibi yüksek puanlı okulları hedeflemenizi sağlıyoruz.",
    featuredFacts: [{ label: "Puanlama", value: "Maksimum 90 Puan (+1.5 Doğru, -0.4 Yanlış)" }, { label: "Yetkili Kurum", value: "İtalya Üniversite ve Araştırma Bakanlığı (MUR)" }],
    faqs: [
      { question: "IMAT için İtalyanca bilmek gerekir mi?", answer: "Hayır. Sınav ve eğitim dili tamamen İngilizcedir." },
      { question: "Hangi üniversiteler IMAT ile öğrenci alır?", answer: "University of Milan, Sapienza Rome, Bologna, Pavia, Padova, Tor Vergata ve diğer İtalyan devlet tıp fakülteleri." },
    ],
    cta: { title: "İtalya'da İngilizce tıp eğitiminizi planlayın.", body: "Mevcut fen ve matematik seviyenizi değerlendirerek size özel bir IMAT hazırlık rotası kuralım.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  GAMSAT: {
    seoTitle: "GAMSAT Hazırlık ve Lisansüstü Tıp Danışmanlığı | Oriens Academy",
    seoDescription: "UK, Avustralya ve İrlanda Graduate Entry Medicine (GEM) programları için GAMSAT Section I, II ve III hazırlığı.",
    overview: [
      "Graduate Medical School Admissions Test (GAMSAT), üniversite mezunlarının tıp, diş hekimliği ve veterinerlik programlarına kabulünde kullanılan ileri düzey bir seçme sınavıdır.",
      "Sosyal bilimler, yazılı iletişim ve biyolojik/fiziksel bilimlerde karmaşık kavramları kavrama ve problem çözme yeteneğini ölçer.",
    ],
    preparationAreas: [
      { title: "Section I (Humanities & Social Sciences)", description: "Edebi ve felsefi metinleri, şiir ve sosyolojik analizleri derinlemesine anlama pratiği yaparız." },
      { title: "Section II (Written Communication)", description: "Farklı sosyo-kültürel temalarda derinlikli, özgün ve analitik iki adet deneme yazmayı çalışırız." },
      { title: "Section III (Biological & Physical Sciences)", description: "Üniversite 1. sınıf kimya ve biyoloji ile lise düzeyi fizik konularında veri temelli problem çözümü uygularız." },
    ],
    oriensSupport: "Fen geçmişi olan veya olmayan adaylara yönelik dengeli çalışma takvimi, essay analizleri ve bilimsel akıl yürütme mentörlüğü sunuyoruz.",
    featuredFacts: [{ label: "Sağlayıcı", value: "ACER (Australian Council for Educational Research)" }, { label: "Kapsam", value: "Graduate Entry Medicine (UK, İrlanda, Avustralya)" }],
    faqs: [
      { question: "Fen bölümü mezunu olmayanlar GAMSAT alabilir mi?", answer: "Evet. GAMSAT ezberden ziyade verilen bilimsel veriyi anlama ve akıl yürütme becerisini ölçtüğü için her bölümden mezun adaylar hazırlanabilir." },
    ],
    cta: { title: "Lisansüstü tıp kariyerinize ilk adımı atın.", body: "GAMSAT beceri profilinizi uzmanlarımızla değerlendirerek kişisel çalışma planınızı çıkarın.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  MCAT: {
    seoTitle: "MCAT Hazırlık ve ABD/Kanada Tıp Eğitimi | Oriens Academy",
    seoDescription: "ABD ve Kanada tıp fakülteleri kabulleri için MCAT Chemical/Physical, CARS, Biological ve Psychological Foundations hazırlığı.",
    overview: [
      "Medical College Admission Test (MCAT), Association of American Medical Colleges (AAMC) tarafından düzenlenen ve Kuzey Amerika tıp fakültelerinin (MD/DO) vazgeçilmez kabul sınavıdır.",
      "Doğa bilimleri, davranış bilimleri ve eleştirel okuma alanlarındaki bilgilerin karmaşık biyomedikal senaryolarda uygulanmasını ölçer.",
    ],
    preparationAreas: [
      { title: "Biological & Biochemical Foundations", description: "Biyokimya, moleküler biyoloji ve organ sistemleri arasındaki entegre süreçleri derinlemesine kavratırız." },
      { title: "Chemical & Physical Foundations", description: "Genel kimya, organik kimya ve fiziğin biyolojik sistemlerdeki işleyişini problem odaklı çalışırız." },
      { title: "CARS (Critical Analysis and Reasoning Skills)", description: "Akademik pasajlarda yazar tonu, argüman yapısı ve örtük varsayımları hızla analiz etmeyi öğretiriz." },
      { title: "Psychological & Social Foundations", description: "Davranış bilimleri, psikoloji ve sosyoloji kavramlarının sağlık bağlamındaki uygulamalarını inceleriz." },
    ],
    oriensSupport: "7.5 saatlik bu zorlu sınav için içerik hâkimiyeti, AAMC soru stili pratiği ve zihinsel dayanıklılık kazandıran simülasyon takvimi uyguluyoruz.",
    featuredFacts: [{ label: "Puanlama Skalası", value: "472–528 Toplam Puan" }, { label: "Kullanım", value: "ABD ve Kanada Tıp Fakülteleri (AMCAS / AACOMAS / OMSAS)" }],
    faqs: [
      { question: "MCAT için önerilen hazırlık süresi nedir?", answer: "Kapsamın genişliği nedeniyle haftalık 15-20 saatlik çalışmayla en az 4-6 aylık planlama önerilir." },
      { question: "CARS bölümü için nasıl çalışılır?", answer: "CARS ön bilgi gerektirmez; bilim dışı beşeri metinleri derinlemesine okuma, argüman haritalama ve düzenli pratikle geliştirilir." },
    ],
    cta: { title: "Kuzey Amerika tıp fakültesi hedefinize odaklanın.", body: "MCAT seviyenizi belirleyin ve 515+ puan hedefli birebir çalışma sisteminizi başlatın.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  LSAT: {
    seoTitle: "LSAT Hazırlık ve JD Hukuk Kabulleri | Oriens Academy",
    seoDescription: "ABD, Kanada ve uluslararası JD hukuk programları için LSAT Logical Reasoning ve Reading Comprehension hazırlığı.",
    overview: [
      "Law School Admission Test (LSAT), Law School Admission Council (LSAC) tarafından yönetilen ve prestijli hukuk fakültelerinin JD kabullerinde en kritik kriter olan sınavdır.",
      "Hukuk formasyonunun temeli olan katı mantıksal akıl yürütme, çıkarım gücü ve karmaşık argüman çözümleme becerilerini test eder.",
    ],
    preparationAreas: [
      { title: "Logical Reasoning (Mantıksal Akıl Yürütme)", description: "Varsayım bulma, argümanı güçlendirme/zayıflatma, kusurlu akıl yürütme ve paralel mantık kalıplarını öğretiriz." },
      { title: "Reading Comprehension (Eleştirel Okuma)", description: "Hukuki, felsefi ve bilimsel metinlerde argüman yapısı, karşıt tezler ve yazar perspektifini çözümletiriz." },
      { title: "Sınav Stratejisi ve Süre Disiplini", description: "Bölüm başına düşen dar sürede tuzak seçenekleri hızla eleyerek %99 percentile hedefi için hız kazandırırız." },
    ],
    oriensSupport: "Mantık hatalarını ve önerme kalıplarını sezgisel değil matematiksel kesinlikte çözen bir düşünme sistemi kazandırıyoruz.",
    featuredFacts: [{ label: "Puan Skalası", value: "120–180 Standart Puan" }, { label: "Kullanım", value: "T14 ve tüm ABD / Kanada Hukuk Fakülteleri (JD)" }],
    faqs: [
      { question: "LSAT'ta hukuk bilgisi sorulur mu?", answer: "Hayır. Tamamen soyut mantık, eleştirel düşünme ve analitik okuma yeteneğini ölçer." },
      { question: "İyi bir JD programı için kaç puan gerekir?", answer: "En üst sıralamadaki (T14) hukuk okulları genellikle 170+ puan aralığını hedefler." },
    ],
    cta: { title: "T14 hukuk fakülteleri için 170+ puanı hedefleyin.", body: "Mantıksal akıl yürütme seviyenizi test edelim ve hedefinize özel LSAT çalışma planını kuralım.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  GRE: {
    seoTitle: "GRE Hazırlık ve Birebir Destek | Oriens Academy",
    seoDescription: "GRE Verbal, Quantitative ve Analytical Writing alanları için teşhis odaklı çalışma planı ve birebir hazırlık desteği.",
    overview: ["GRE General Test; sözel akıl yürütme, nicel akıl yürütme, eleştirel düşünme ve analitik yazma becerilerini değerlendiren bir lisansüstü kabul sınavıdır.", "Hangi programların GRE sonucu istediği veya kabul ettiği değişebilir; adaylar hedef kurumlarının güncel koşullarını kontrol etmelidir."],
    preparationAreas: [
      { title: "Quantitative Reasoning", description: "Nicel bilgiyi yorumlama, matematiksel model kurma ve temel kavramları uygulama pratiği yaparız." },
      { title: "Verbal Reasoning", description: "Akademik metinleri çözümleme, çıkarım ve kelime ilişkileri üzerinde çalışırız." },
      { title: "Analytical Writing", description: "Karmaşık fikirleri açık tez, gerekçe ve örneklerle geliştirme becerisini güçlendiririz." },
    ],
    oriensSupport: "Başlangıç performansına göre alan öncelikleri belirlenir. Sözel, nicel ve yazılı çalışma dengesi adayın program hedefi ve hazırlık süresine göre düzenlenir.",
    featuredFacts: [{ label: "Beceri alanları", value: "Verbal · Quantitative · Analytical Writing" }, { label: "Kullanım bağlamı", value: "Lisansüstü program başvuruları" }],
    faqs: [
      { question: "GRE her lisansüstü program için zorunlu mudur?", answer: "Hayır. Politika kurum ve programa göre değişir; güncel başvuru koşulları doğrudan kontrol edilmelidir." },
      { question: "Quantitative hazırlık ileri matematik gerektirir mi?", answer: "Odak, resmî kapsam içindeki temel matematiksel kavramları yorumlama ve problem çözmede doğru kullanmaktır." },
      { question: "Sözel ve nicel alanlar ayrı planlanabilir mi?", answer: "Evet. Başlangıç değerlendirmesine göre alan ağırlıkları kişiselleştirilebilir." },
    ],
    cta: { title: "GRE hazırlığınızı lisansüstü hedefinize göre planlayalım.", body: "Sözel, nicel ve yazılı becerileriniz için dengeli ve izlenebilir bir çalışma rotası kuralım.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  GMAT: {
    seoTitle: "GMAT Focus Hazırlık ve Birebir Destek | Oriens Academy",
    seoDescription: "GMAT Focus Quantitative Reasoning, Verbal Reasoning ve Data Insights alanları için kişiselleştirilmiş hazırlık desteği.",
    overview: ["GMAT Focus Edition, lisansüstü işletme eğitimi bağlamında nicel, sözel ve veri odaklı akıl yürütme becerilerini değerlendiren bir kabul sınavıdır.", "Programların sınav politikaları farklılaşabilir; GMAT kararı hedef işletme okullarının güncel kabul sayfalarıyla birlikte değerlendirilmelidir."],
    preparationAreas: [
      { title: "Quantitative Reasoning", description: "Aritmetik ve cebir temelini mantık ve problem çözme kararlarıyla birleştiririz." },
      { title: "Verbal Reasoning", description: "Yazılı materyali anlama, argüman değerlendirme ve çıkarım becerilerini geliştiririz." },
      { title: "Data Insights", description: "Grafik, tablo ve çoklu kaynaklardan veriyi yorumlayıp karar üretmeyi çalışırız." },
    ],
    oriensSupport: "Üç beceri alanını tek teşhis sistemi içinde ele alırız. Veri okuryazarlığı, çözüm verimliliği ve yanlış analizi düzenli ilerleme görüşmeleriyle takip edilir.",
    featuredFacts: [{ label: "Bölüm eksenleri", value: "Quantitative · Verbal · Data Insights" }, { label: "Akademik hedef", value: "Lisansüstü işletme ve MBA programları" }],
    faqs: [
      { question: "GMAT yalnızca MBA başvurularında mı kullanılır?", answer: "GMAT farklı lisansüstü işletme ve finans programlarında kullanılabilir; her programın güncel politikasını kontrol etmek gerekir." },
      { question: "Data Insights için nasıl hazırlanılır?", answer: "Tablo, grafik, metin ve nicel veriyi birlikte okuma; ilgili bilgiyi seçme ve çıkarım yapma pratikleriyle hazırlanılır." },
      { question: "GRE ile GMAT arasında nasıl seçim yapılır?", answer: "Hedef programların kabul politikaları ve adayın beceri profili birlikte değerlendirilmelidir." },
    ],
    cta: { title: "GMAT hazırlığınızı işletme okulu hedefinize bağlayalım.", body: "Beceri profilinizi değerlendirerek nicel, sözel ve veri odaklı çalışma dengesini oluşturalım.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  OMPT: {
    seoTitle: "OMPT Hazırlık ve Matematik Desteği | Oriens Academy",
    seoDescription: "Hollanda ve Avrupa üniversiteleri OMPT matematik sınavı için konu analizi, kavram tekrarı ve birebir problem çözme desteği.",
    overview: ["OMPT, üniversitelerin uluslararası adayların programa uygun matematik yeterliliğini değerlendirmek için kullanabildiği çevrim içi kabul sınavları ailesidir.", "Farklı OMPT türleri farklı konu kapsamlarına sahip olduğundan adayın hazırlığı, üniversitenin istediği kesin test türü doğrulandıktan sonra planlanmalıdır."],
    preparationAreas: [
      { title: "Test türünü doğrulama", description: "Önce hedef programın istediği OMPT varyantını ve resmî konu kapsamını netleştiririz." },
      { title: "Kavram yenileme", description: "Gerekli cebir, fonksiyon, kalkülüs, geometri veya istatistik konularını ihtiyaca göre çalışırız." },
      { title: "Dijital problem çözme", description: "Çevrim içi matematik gösterimi ve kontrollü çözüm adımları için uygulama yaparız." },
    ],
    oriensSupport: "Hazırlık, genel bir OMPT varsayımıyla değil öğrencinin kesin test türü ve program şartıyla başlar. Konu eksiği, pratik ve geri bildirim bu kapsama göre kişiselleştirilir.",
    featuredFacts: [{ label: "Sınav ailesi", value: "Programa göre farklı matematik testleri" }, { label: "İlk adım", value: "Doğru OMPT türünü doğrulamak" }],
    faqs: [
      { question: "Hangi OMPT sınavına girmeliyim?", answer: "Bunu hedef üniversite veya program belirler. Kayıt ve hazırlık öncesinde kabul ofisinin güncel şartını kontrol edin." },
      { question: "Tüm OMPT türlerinin konu kapsamı aynı mıdır?", answer: "Hayır. OMPT varyantlarının kapsamı farklıdır; yalnızca ilgili testin resmî konu kapsamı üzerinden çalışılmalıdır." },
      { question: "Oriens yalnızca eksik olduğum konulara odaklanabilir mi?", answer: "Evet. Tanılama sonucuna ve test kapsamına göre konu ağırlıkları kişiselleştirilebilir." },
    ],
    cta: { title: "Doğru OMPT rotasını birlikte belirleyelim.", body: "Programınızın istediği test türünü ve matematik seviyenizi değerlendirerek odaklı bir çalışma planı oluşturalım.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
};
