import type { ExamDetailTextMap } from "../exams";

export const examDetailText: ExamDetailTextMap = {
  IB: {
    seoTitle: "IB Hazırlık ve Akademik Destek | Oriens Academy",
    seoDescription: "IB Diploma Programme dersleri, iç değerlendirmeler ve sınavlar için kişiselleştirilmiş akademik destek ve çalışma planlaması.",
    overview: [
      "International Baccalaureate Diploma Programme, farklı akademik alanları DP çekirdeğiyle bir araya getiren bütünlüklü bir lise programıdır.",
      "Hazırlık yalnızca final sınavlarına değil; ders seçimi, kavramsal derinlik, iç değerlendirmeler ve uzun dönemli çalışma düzenine birlikte bakmayı gerektirir.",
    ],
    preparationAreas: [
      { title: "Ders temeli", description: "Matematik ve fen derslerinde eksik kavramları belirleyip HL veya SL kapsamına uygun biçimde tamamlarız." },
      { title: "Değerlendirme dili", description: "Soru yönergelerini, çözüm sunumunu ve markscheme beklentilerini sistemli çalışırız." },
      { title: "IA planlaması", description: "Araştırma sorusu, yöntem ve akademik anlatım süreçlerinde etik sınırlar içinde rehberlik sağlarız." },
    ],
    oriensSupport: "Ders bazlı özel çalışmayı dönem planı, değerlendirme takvimi ve düzenli ilerleme takibiyle birleştiriyoruz. Öğrencinin okul programı ve seçtiği ders düzeyleri hazırlık rotasının temelini oluşturur.",
    featuredFacts: [{ label: "Program yapısı", value: "Ders grupları ve DP çekirdeği" }, { label: "Hazırlık odağı", value: "Dersler, değerlendirmeler ve akademik planlama" }],
    faqs: [
      { question: "IB desteği yalnızca final sınavlarına mı yöneliktir?", answer: "Hayır. Ders içeriği, iç değerlendirmeler, çalışma düzeni ve sınav hazırlığı öğrencinin ihtiyacına göre birlikte ele alınabilir." },
      { question: "HL ve SL öğrencileri için plan farklılaşır mı?", answer: "Evet. Ders düzeyi, okulun ilerleme sırası ve öğrencinin hedefleri çalışma kapsamını doğrudan belirler." },
      { question: "IA çalışmasında nasıl destek verilir?", answer: "Konu netleştirme, yöntem, yapı ve geri bildirim sağlanır; öğrencinin özgün çalışması korunur ve çalışma onun yerine yazılmaz." },
    ],
    cta: { title: "IB hazırlık rotanızı birlikte planlayalım.", body: "Derslerinizi, yaklaşan değerlendirmeleri ve hedeflerinizi konuşarak sürdürülebilir bir akademik plan oluşturalım.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  AP: {
    seoTitle: "AP Hazırlık ve Özel Ders | Oriens Academy",
    seoDescription: "AP Calculus, Statistics, Physics ve Chemistry dersleri için konu odaklı hazırlık, soru pratiği ve birebir akademik destek.",
    overview: ["Advanced Placement, lise öğrencilerinin üniversite düzeyindeki belirli dersleri ve bunlara bağlı değerlendirmeleri takip edebildiği konu bazlı bir programdır.", "Her AP dersinin kapsamı ve değerlendirme biçimi farklıdır; bu nedenle hazırlık seçilen dersin resmî çerçevesi üzerinden kurulmalıdır."],
    preparationAreas: [
      { title: "Konu haritası", description: "Seçilen AP dersinin ünitelerini mevcut bilgi düzeyiyle eşleştiririz." },
      { title: "Soru türleri", description: "Çoktan seçmeli, serbest yanıt veya derse özgü görevler için uygun çözüm yaklaşımı geliştiririz." },
      { title: "Deneme analizi", description: "Yanlışları konu, yorum ve zaman yönetimi boyutlarında sınıflandırırız." },
    ],
    oriensSupport: "Oriens desteği seçilen AP dersine göre özelleşir. Konu anlatımı, kontrollü soru pratiği ve geri bildirim döngüsü öğrencinin okul temposuyla birlikte planlanır.",
    featuredFacts: [{ label: "Yapı", value: "Ders ve sınav bazlı" }, { label: "Oriens odağı", value: "Matematik ve fen derslerinde derinleşme" }],
    faqs: [
      { question: "Her AP dersi için aynı hazırlık planı kullanılabilir mi?", answer: "Hayır. Ders kapsamı ve değerlendirme biçimi değiştiği için plan seçilen AP dersine göre hazırlanır." },
      { question: "AP sonucu üniversite kredisi sağlar mı?", answer: "Kredi ve yerleştirme politikaları kuruma göre değişir. Hedef üniversitenin güncel politikasını doğrudan kontrol etmek gerekir." },
      { question: "Hazırlığa ne zaman başlanmalı?", answer: "Başlangıç zamanı öğrencinin konu temeline, okul programına ve hedeflediği derslere göre belirlenmelidir." },
    ],
    cta: { title: "AP dersiniz için net bir çalışma sistemi kuralım.", body: "Seçtiğiniz AP dersini ve mevcut seviyenizi değerlendirerek konu ve soru pratiği rotasını belirleyelim.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  SAT: {
    seoTitle: "SAT Hazırlık ve Özel Ders | Oriens Academy",
    seoDescription: "Digital SAT Reading and Writing ile Math alanları için kişiselleştirilmiş hazırlık, deneme analizi ve birebir akademik destek.",
    overview: ["SAT, okuma-yazma ve matematik becerilerini ölçen dijital bir sınavdır ve bazı lisans başvurularında akademik değerlendirme unsuru olarak kullanılabilir.", "Kurumların SAT politikaları farklılaşabildiği için sınav kararı hedef üniversitelerin güncel kabul şartlarıyla birlikte değerlendirilmelidir."],
    preparationAreas: [
      { title: "Reading & Writing", description: "Kısa metinlerde kanıt, bağlam, dil bilgisi ve anlatım kararlarını birlikte çalışırız." },
      { title: "Matematik", description: "Cebir, problem çözme, veri analizi ve ileri matematik konularında kavram-uygulama bağını güçlendiririz." },
      { title: "Dijital sınav stratejisi", description: "Modül düzeni, araç kullanımı ve deneme sonrası hata analizi için tekrar edilebilir bir sistem kurarız." },
    ],
    oriensSupport: "Başlangıç değerlendirmesinden sonra konu eksikleri, soru yaklaşımı ve deneme performansı tek planda birleştirilir. İlerleme, yalnızca toplam sonuçla değil hata türleri ve çözüm kalitesiyle izlenir.",
    featuredFacts: [{ label: "Değerlendirme alanları", value: "Reading & Writing · Math" }, { label: "Hazırlık modeli", value: "Teşhis · çalışma · deneme analizi" }],
    faqs: [
      { question: "SAT hangi öğrenciler için anlamlıdır?", answer: "SAT isteyen, kabul eden veya başvurusunda sınav sonucu kullanmayı değerlendiren lisans adayları için anlamlı olabilir. Hedef kurum politikaları kontrol edilmelidir." },
      { question: "SAT hazırlığı yalnızca deneme çözmekten mi oluşur?", answer: "Hayır. Denemeler teşhis aracıdır; kalıcı gelişim için konu temeli, soru çözümü ve yanlış analizi birlikte yürütülür." },
      { question: "Oriens birebir SAT desteği sağlar mı?", answer: "Evet. Çalışma kapsamı öğrencinin mevcut seviyesi, hedefi ve müsait zamanına göre kişiselleştirilebilir." },
    ],
    cta: { title: "SAT hazırlık sürecinizi birlikte planlayalım.", body: "Mevcut seviyenizi ve başvuru hedeflerinizi konuşarak ölçülebilir bir çalışma rotası oluşturalım.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  ESAT: {
    seoTitle: "ESAT Hazırlık ve Akademik Destek | Oriens Academy",
    seoDescription: "ESAT matematik ve fen modülleri için ders temeli, uygulamalı problem çözme ve sınav odaklı birebir hazırlık.",
    overview: ["Engineering and Science Admissions Test, seçili mühendislik ve fen programlarının başvurularında kullanılabilen modüler bir kabul sınavıdır.", "Adayın çalışması gereken modüller başvurduğu programa göre değişebildiği için hazırlık öncesinde üniversitenin güncel ders sayfası kontrol edilmelidir."],
    preparationAreas: [
      { title: "Zorunlu matematik temeli", description: "Matematik bilgisini yeni durumlarda uygulama ve kısa çözüm yolu geliştirme üzerine çalışırız." },
      { title: "Programa uygun modüller", description: "Fizik, kimya, biyoloji veya ileri matematik çalışmasını gerçek başvuru gerekliliğine göre seçeriz." },
      { title: "Teknik problem çözme", description: "Bilgiyi tanımaktan öte, verilen koşullara hızlı ve kontrollü biçimde uygulamayı geliştiririz." },
    ],
    oriensSupport: "Önce hedef programın istediği modülleri netleştirir, ardından konu kontrol listesi ve zamanlı problem çözme pratiği oluştururuz. Hazırlık, resmî spesifikasyonla uyumlu tutulur.",
    featuredFacts: [{ label: "Sınav yaklaşımı", value: "Matematik ve fen bilgisini uygulama" }, { label: "Modül seçimi", value: "Hedef programa göre değişir" }],
    faqs: [
      { question: "Hangi ESAT modüllerine hazırlanmalıyım?", answer: "Bu, başvurduğunuz programa bağlıdır. Üniversitenin güncel program sayfasındaki gereklilikler esas alınmalıdır." },
      { question: "ESAT hazırlığında okul bilgisi yeterli midir?", answer: "Resmî sınav mevcut okul bilgisini uygulamaya odaklanır; yine de eksik konu ve yeni problem türleri için hedefli pratik gerekir." },
      { question: "Oriens fen ve matematik modüllerini birlikte planlar mı?", answer: "Evet. İstenen modül kombinasyonuna göre dersler tek bir hazırlık takviminde koordine edilebilir." },
    ],
    cta: { title: "ESAT modül rotanızı netleştirelim.", body: "Hedef programınızı ve ders temelinizi değerlendirerek doğru modüllere odaklanan bir hazırlık planı kuralım.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  TARA: {
    seoTitle: "TARA Hazırlık ve Akademik Rehberlik | Oriens Academy",
    seoDescription: "TARA eleştirel düşünme, problem çözme ve yazma görevi için yapılandırılmış pratik ve birebir akademik rehberlik.",
    overview: ["Test of Academic Reasoning for Admissions, belirli bir ders bilgisinden çok lisans eğitimi için gerekli genel düşünme ve açık ifade becerilerine odaklanır.", "Sınav gerekliliği programa göre değiştiğinden adaylar başvurdukları kurumun güncel kabul sayfasını kontrol etmelidir."],
    preparationAreas: [
      { title: "Eleştirel düşünme", description: "İddia, gerekçe, varsayım ve sonuç ilişkilerini dikkatle çözümlemeyi çalışırız." },
      { title: "Problem çözme", description: "Veriyi düzenleme, koşulları ayırma ve uygun yöntemi seçme alışkanlığı geliştiririz." },
      { title: "Yazılı ifade", description: "Açık tez, mantıklı yapı ve kanıta dayalı anlatım için zamanlı yazma pratiği yaparız." },
    ],
    oriensSupport: "Konu ezberinden bağımsız olarak düşünme süreçlerini görünür hâle getiririz. Zamanlı uygulamalar, çözüm tartışmaları ve yazılı geri bildirim aynı planda ilerler.",
    featuredFacts: [{ label: "Odak", value: "Genel akademik akıl yürütme" }, { label: "Çalışma alanları", value: "Eleştirel düşünme · problem çözme · yazma" }],
    faqs: [
      { question: "TARA için belirli bir ders müfredatı çalışmak gerekir mi?", answer: "TARA konuya özgü bilgi gerektirmeyen genel becerilere odaklanır; hazırlık formatı ve düşünme süreçlerini tanımaya yönelmelidir." },
      { question: "Yazma görevi için nasıl hazırlanılır?", answer: "Fikir üretme, yapı kurma, gerekçelendirme ve süre içinde açık anlatım pratikleriyle hazırlanılır." },
      { question: "Her Oxford veya UCL adayı TARA alır mı?", answer: "Hayır. Gereklilik programa göre değişebilir; ilgili üniversitenin güncel ders sayfası kontrol edilmelidir." },
    ],
    cta: { title: "TARA düşünme ve yazma rotanızı kuralım.", body: "Akıl yürütme yaklaşımınızı değerlendirerek odaklı pratik ve geri bildirim planı oluşturalım.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  TMUA: {
    seoTitle: "TMUA Hazırlık ve Matematik Özel Ders | Oriens Academy",
    seoDescription: "TMUA matematiksel bilgi uygulaması, akıl yürütme ve mantık alanları için birebir hazırlık ve problem çözme desteği.",
    overview: ["Test of Mathematics for University Admission, matematik veya matematik yoğun programlara başvuran adayların matematik bilgisini yeni durumlarda kullanma ve akıl yürütme becerisini değerlendirmek için kullanılır.", "TMUA gerekliliği ve sonucun kullanım biçimi kurum ve programa göre değişebilir; güncel koşullar resmî üniversite sayfasından doğrulanmalıdır."],
    preparationAreas: [
      { title: "Bilgiyi uygulama", description: "Standart konuları alışılmadık soru bağlamlarında esnek biçimde kullanmayı geliştiririz." },
      { title: "Matematiksel akıl yürütme", description: "Önermeler, gereklilik-yeterlilik ve mantıksal çıkarım üzerinde çalışırız." },
      { title: "Çözüm verimliliği", description: "Alternatif yolları karşılaştırıp kontrollü ve ekonomik çözüm seçmeyi pratik ederiz." },
    ],
    oriensSupport: "Konu tekrarını, matematiksel muhakeme ve zamanlı soru setleriyle birleştiriyoruz. Yanlışlar yalnızca sonuç üzerinden değil, kullanılan varsayım ve çözüm yolu üzerinden incelenir.",
    featuredFacts: [{ label: "Ana eksen", value: "Matematiksel uygulama ve akıl yürütme" }, { label: "İlgili programlar", value: "Matematik yoğun lisans alanları" }],
    faqs: [
      { question: "TMUA ileri matematik bilgisi mi, akıl yürütme mi ölçer?", answer: "Sınav belirlenmiş matematik içeriğini yeni durumlara uygulama ve matematiksel akıl yürütme becerisine odaklanır; ikisi birlikte çalışılmalıdır." },
      { question: "TMUA için yalnızca konu tekrarı yeterli midir?", answer: "Genellikle hayır. Konu hâkimiyetinin yanında mantık dili, yeni problem türleri ve zamanlı uygulama gerekir." },
      { question: "Hedef üniversitem TMUA istiyor mu?", answer: "Gereklilikler değişebilir. Başvuru döneminde üniversitenizin ilgili program sayfasını kontrol edin." },
    ],
    cta: { title: "TMUA matematik rotanızı birlikte çizelim.", body: "Konu temeliniz ve problem çözme yaklaşımınız üzerinden kişiselleştirilmiş bir çalışma sistemi oluşturalım.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  IGCSE: {
    seoTitle: "IGCSE Hazırlık ve Ders Desteği | Oriens Academy",
    seoDescription: "Cambridge IGCSE matematik ve fen derslerinde müfredat takibi, kavram tekrarı ve sınav odaklı birebir akademik destek.",
    overview: ["Cambridge IGCSE, okulların farklı ders kombinasyonları oluşturabildiği uluslararası bir ortaöğretim programı ve yeterlilik sistemidir.", "Değerlendirme biçimi derse göre değişebildiğinden hazırlık, öğrencinin kesin ders kodu ve güncel müfredat belgesi üzerinden yürütülmelidir."],
    preparationAreas: [
      { title: "Syllabus takibi", description: "Ders koduna ait güncel kapsamı okul ilerleyişiyle eşleştiririz." },
      { title: "Kavramsal temel", description: "Matematik ve fen konularında ezber yerine neden-sonuç ilişkisini güçlendiririz." },
      { title: "Sınav uygulaması", description: "Geçmiş sorular ve değerlendirme dili üzerinden cevap kalitesini geliştiririz." },
    ],
    oriensSupport: "Öğrencinin aldığı IGCSE dersini ve okul takvimini temel alan düzenli destek sağlıyoruz. Konu anlatımı, ödev yaklaşımı ve sınav pratiği aynı ilerleme planında buluşur.",
    featuredFacts: [{ label: "Program yaklaşımı", value: "Esnek ders kombinasyonları" }, { label: "Oriens kapsamı", value: "Matematik ve fen ders desteği" }],
    faqs: [
      { question: "Tüm IGCSE derslerinin sınav yapısı aynı mıdır?", answer: "Hayır. Yazılı, sözlü, ders içi çalışma veya uygulamalı değerlendirmeler derse göre değişebilir; doğru müfredat kontrol edilmelidir." },
      { question: "Core ve Extended kapsamı hazırlığı etkiler mi?", answer: "Evet. İlgili derste seçenek bulunuyorsa öğrencinin takip ettiği kapsam çalışma planını belirler." },
      { question: "Okul dersleriyle paralel destek alınabilir mi?", answer: "Evet. Plan okulun konu sırası ve yaklaşan değerlendirmeleriyle uyumlu kurulabilir." },
    ],
    cta: { title: "IGCSE derslerinizi sağlam bir temele oturtalım.", body: "Ders kodlarınızı ve okul planınızı inceleyerek düzenli, konu odaklı bir destek rotası oluşturalım.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  GRE: {
    seoTitle: "GRE Hazırlık ve Birebir Destek | Oriens Academy",
    seoDescription: "GRE Verbal, Quantitative ve Analytical Writing alanları için teşhis odaklı çalışma planı ve birebir hazırlık desteği.",
    overview: ["GRE General Test; sözel akıl yürütme, nicel akıl yürütme, eleştirel düşünme ve analitik yazma becerilerini değerlendiren bir lisansüstü kabul sınavıdır.", "Hangi programların GRE sonucu istediği veya kabul ettiği değişebilir; adaylar hedef kurumlarının güncel koşullarını kontrol etmelidir."],
    preparationAreas: [
      { title: "Quantitative Reasoning", description: "Nicel bilgiyi yorumlama, matematiksel model kurma ve temel kavramları uygulama pratiği yaparız." },
      { title: "Verbal Reasoning", description: "Akademik metinleri çözümleme, çıkarım ve kelime ilişkileri üzerinde çalışırız." },
      { title: "Analytical Writing", description: "Karmaşık fikirleri açık tez, gerekçe ve örneklerle geliştirme becerisini güçlendiririz." },
    ],
    oriensSupport: "Başlangıç performansına göre alan öncelikleri belirlenir. Sözel, nicel ve yazılı çalışma dengesi adayın program hedefi ve hazırlık süresine göre düzenlenir.",
    featuredFacts: [{ label: "Beceri alanları", value: "Verbal · Quantitative · Analytical Writing" }, { label: "Kullanım bağlamı", value: "Lisansüstü program başvuruları" }],
    faqs: [
      { question: "GRE her lisansüstü program için zorunlu mudur?", answer: "Hayır. Politika kurum ve programa göre değişir; güncel başvuru koşulları doğrudan kontrol edilmelidir." },
      { question: "Quantitative hazırlık ileri matematik gerektirir mi?", answer: "Odak, resmî kapsam içindeki temel matematiksel kavramları yorumlama ve problem çözmede doğru kullanmaktır." },
      { question: "Sözel ve nicel alanlar ayrı planlanabilir mi?", answer: "Evet. Başlangıç değerlendirmesine göre alan ağırlıkları kişiselleştirilebilir." },
    ],
    cta: { title: "GRE hazırlığınızı lisansüstü hedefinize göre planlayalım.", body: "Sözel, nicel ve yazılı becerileriniz için dengeli ve izlenebilir bir çalışma rotası kuralım.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  GMAT: {
    seoTitle: "GMAT Hazırlık ve Birebir Destek | Oriens Academy",
    seoDescription: "GMAT Quantitative Reasoning, Verbal Reasoning ve Data Insights alanları için kişiselleştirilmiş hazırlık desteği.",
    overview: ["GMAT, lisansüstü işletme eğitimi bağlamında nicel, sözel ve veri odaklı akıl yürütme becerilerini değerlendiren bir kabul sınavıdır.", "Programların sınav politikaları farklılaşabilir; GMAT kararı hedef işletme okullarının güncel kabul sayfalarıyla birlikte değerlendirilmelidir."],
    preparationAreas: [
      { title: "Quantitative Reasoning", description: "Aritmetik ve cebir temelini mantık ve problem çözme kararlarıyla birleştiririz." },
      { title: "Verbal Reasoning", description: "Yazılı materyali anlama, argüman değerlendirme ve çıkarım becerilerini geliştiririz." },
      { title: "Data Insights", description: "Grafik, tablo ve çoklu kaynaklardan veriyi yorumlayıp karar üretmeyi çalışırız." },
    ],
    oriensSupport: "Üç beceri alanını tek teşhis sistemi içinde ele alırız. Veri okuryazarlığı, çözüm verimliliği ve yanlış analizi düzenli ilerleme görüşmeleriyle takip edilir.",
    featuredFacts: [{ label: "Bölüm eksenleri", value: "Quantitative · Verbal · Data Insights" }, { label: "Akademik hedef", value: "Lisansüstü işletme programları" }],
    faqs: [
      { question: "GMAT yalnızca MBA başvurularında mı kullanılır?", answer: "GMAT farklı lisansüstü işletme programlarında kullanılabilir; her programın güncel politikasını kontrol etmek gerekir." },
      { question: "Data Insights için nasıl hazırlanılır?", answer: "Tablo, grafik, metin ve nicel veriyi birlikte okuma; ilgili bilgiyi seçme ve çıkarım yapma pratikleriyle hazırlanılır." },
      { question: "GRE ile GMAT arasında nasıl seçim yapılır?", answer: "Hedef programların kabul politikaları ve adayın beceri profili birlikte değerlendirilmelidir." },
    ],
    cta: { title: "GMAT hazırlığınızı işletme okulu hedefinize bağlayalım.", body: "Beceri profilinizi değerlendirerek nicel, sözel ve veri odaklı çalışma dengesini oluşturalım.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  UKCAT: {
    seoTitle: "UCAT (UKCAT) Hazırlık ve Rehberlik | Oriens Academy",
    seoDescription: "UCAT olarak devam eden UKCAT için sözel, karar verme, nicel ve durumsal yargı alanlarında birebir hazırlık desteği.",
    overview: ["UKCAT adıyla başlayan ve günümüzde UCAT olarak yürütülen sınav, tıp ve diş hekimliği programlarının önemli gördüğü bilişsel beceriler ile durumsal yargıyı değerlendirir.", "Kullanan kurumlar ve değerlendirme politikaları değişebildiğinden adaylar UCAT Consortium ve hedef üniversitelerin güncel bilgilerini kontrol etmelidir."],
    preparationAreas: [
      { title: "Sözel ve nicel akıl yürütme", description: "Metin ve sayısal bilgiyi hızla değerlendirirken doğruluğu korumayı çalışırız." },
      { title: "Karar verme", description: "Karmaşık bilgide çıkarım, olasılık ve argüman değerlendirme yaklaşımı geliştiririz." },
      { title: "Durumsal yargı", description: "Profesyonel davranış senaryolarını dikkatle okumayı ve kritik faktörleri ayırmayı pratik ederiz." },
    ],
    oriensSupport: "Bilişsel alanlarda zamanlı pratik ve ayrıntılı yanlış analizi uygularız. Hazırlık, öğrencinin güçlü-zayıf alanlarına göre dengelenir ve garanti sonucu vaadi içermez.",
    featuredFacts: [{ label: "Güncel ad", value: "UCAT" }, { label: "Değerlendirme", value: "Bilişsel beceriler ve durumsal yargı" }],
    faqs: [
      { question: "UKCAT ile UCAT aynı sınav mı?", answer: "UKCAT eski addır; sınav günümüzde UCAT adıyla yürütülmektedir. Güncel bilgi için UCAT Consortium kaynakları kullanılmalıdır." },
      { question: "UCAT bilim bilgisi sınavı mıdır?", answer: "UCAT'ın odağı resmî olarak bilişsel beceriler ve durumsal yargıdır; programların diğer akademik şartları ayrıca değerlendirilir." },
      { question: "Her tıp okulu UCAT ister mi?", answer: "Hayır. Kullanım ve değerlendirme politikaları kuruma göre değişir; hedef okulun güncel sayfası kontrol edilmelidir." },
    ],
    cta: { title: "UCAT hazırlık sisteminizi birlikte kuralım.", body: "Bilişsel alanlarınızı değerlendirerek zamanlı pratik ve geri bildirim odaklı bir rota oluşturalım.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  IMAT: {
    seoTitle: "IMAT Hazırlık ve Akademik Destek | Oriens Academy",
    seoDescription: "İngilizce tıp programlarına yönelik IMAT için biyoloji, kimya, fizik, matematik ve akıl yürütme hazırlık desteği.",
    overview: ["IMAT, İtalya'daki İngilizce yürütülen belirli tıp ve diş hekimliği programlarının ulusal kabul sürecinde kullanılan sınavdır.", "Sınav kapsamı ve başvuru prosedürü akademik döngüye göre güncellenebileceğinden adaylar İtalya Üniversite ve Araştırma Bakanlığının resmî duyurularını takip etmelidir."],
    preparationAreas: [
      { title: "Biyoloji ve kimya", description: "Temel kavramları ilişkilendirip bilimsel soru çözümüne uygulamayı geliştiririz." },
      { title: "Fizik ve matematik", description: "Nicel düşünme, formül seçimi ve problem çözme adımlarını güçlendiririz." },
      { title: "Akıl yürütme", description: "Verilen bilgiyi çözümleyip dikkatli çıkarım yapmaya yönelik pratik uygularız." },
    ],
    oriensSupport: "Bilim derslerini tek bir konu kontrol listesinde toplar, başlangıç düzeyine göre önceliklendiririz. Soru pratiği ve ilerleme takibi akademik rehberlikle birlikte yürür.",
    featuredFacts: [{ label: "Başvuru bağlamı", value: "İngilizce tıp ve diş hekimliği programları" }, { label: "Hazırlık ekseni", value: "Fen bilimleri · matematik · akıl yürütme" }],
    faqs: [
      { question: "IMAT hangi programlar için kullanılır?", answer: "İtalya'daki İngilizce yürütülen belirli tıp ve diş hekimliği programlarının kabul sürecinde kullanılır; güncel program listesi resmî kaynaktan doğrulanmalıdır." },
      { question: "IMAT kapsamı her yıl aynı kalır mı?", answer: "Resmî kapsam ve prosedürler güncellenebilir. Hazırlık öncesinde ilgili akademik yılın bakanlık duyurusu kontrol edilmelidir." },
      { question: "Fen dersleri ayrı ayrı desteklenebilir mi?", answer: "Evet. Öğrencinin eksiğine göre biyoloji, kimya, fizik veya matematik alanlarına farklı ağırlık verilebilir." },
    ],
    cta: { title: "IMAT hazırlığınızı bilimsel bir plana dönüştürelim.", body: "Fen temelinizi ve hedef programınızı değerlendirerek dengeli bir konu ve soru pratiği rotası kuralım.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
  OMPT: {
    seoTitle: "OMPT Hazırlık ve Matematik Desteği | Oriens Academy",
    seoDescription: "Programa göre belirlenen OMPT matematik sınavı için konu analizi, kavram tekrarı ve birebir problem çözme desteği.",
    overview: ["OMPT, üniversitelerin uluslararası adayların programa uygun matematik yeterliliğini değerlendirmek için kullanabildiği çevrim içi kabul sınavları ailesidir.", "Farklı OMPT türleri farklı konu kapsamlarına sahip olduğundan adayın hazırlığı, üniversitenin istediği kesin test türü doğrulandıktan sonra planlanmalıdır."],
    preparationAreas: [
      { title: "Test türünü doğrulama", description: "Önce hedef programın istediği OMPT varyantını ve resmî konu kapsamını netleştiririz." },
      { title: "Kavram yenileme", description: "Gerekli cebir, fonksiyon, kalkülüs, geometri veya istatistik konularını ihtiyaca göre çalışırız." },
      { title: "Dijital problem çözme", description: "Çevrim içi matematik gösterimi ve kontrollü çözüm adımları için uygulama yaparız." },
    ],
    oriensSupport: "Hazırlık, genel bir OMPT varsayımıyla değil öğrencinin kesin test türü ve program şartıyla başlar. Konu eksiği, pratik ve geri bildirim bu kapsama göre kişiselleştirilir.",
    featuredFacts: [{ label: "Sınav ailesi", value: "Programa göre farklı matematik testleri" }, { label: "İlk adım", value: "Doğru OMPT türünü doğrulamak" }],
    faqs: [
      { question: "Hangi OMPT sınavına girmeliyim?", answer: "Bunu hedef üniversite veya program belirler. Kayıt ve hazırlık öncesinde kabul ofisinin güncel şartını kontrol edin." },
      { question: "Tüm OMPT türlerinin konu kapsamı aynı mıdır?", answer: "Hayır. OMPT varyantlarının kapsamı farklıdır; yalnızca ilgili testin resmî konu kapsamı üzerinden çalışılmalıdır." },
      { question: "Oriens yalnızca eksik olduğum konulara odaklanabilir mi?", answer: "Evet. Tanılama sonucuna ve test kapsamına göre konu ağırlıkları kişiselleştirilebilir." },
    ],
    cta: { title: "Doğru OMPT rotasını birlikte belirleyelim.", body: "Programınızın istediği test türünü ve matematik seviyenizi değerlendirerek odaklı bir çalışma planı oluşturalım.", primary: "Ücretsiz Görüşme Planla", secondary: "Tüm Sınavları Gör" },
  },
};
