import type { PricingContent } from "../pricing";

export const pricing = {
  metadata: {
    title: "Ücretler | Oriens Academy",
    description: "Daha fazla ders, daha avantajlı fiyat. Ücretsiz tanışma görüşmesi ve 1, 5, 10, 20, 30 derslik paket seçenekleri.",
  },
  breadcrumb: { ariaLabel: "Sayfa yolu", home: "Ana Sayfa", current: "Ücretler" },
  hero: {
    eyebrow: "Esnek Ders Paketleri",
    title: "Hedefinize uygun çalışma planını seçin.",
    description: "Tek ders desteğinden uzun dönemli hazırlık programlarına kadar ihtiyacınıza ve hedeflerinize uygun çalışma modelini birlikte belirleyebilirsiniz.",
    primaryCta: "Paket Seç, Rezervasyon Yap",
    secondaryCta: "Ücretsiz Tanışma Görüşmesi",
    indexLabel: "5 avantajlı ders paketi",
  },
  packages: {
    eyebrow: "Paketler",
    title: "Daha fazla ders, daha avantajlı birim ücret.",
    intro: "Haziran 2027'ye kadar fiyat garantisi ile şeffaf ve esnek ders paketleri.",
    featuredLabel: "En Çok Tercih Edilen",
    activeLabel: "Aktif paket",
    priceSourceNote: "Program içeriği ve ders planı öğrencinin hedeflerine göre şekillendirilir.",
    customPrice: "İletişime Geçin",
    billingLabels: { session: "/ ders", month: "paket", custom: "Özel" },
    formatStartingPrice: (amount) => `${amount} TL`,
    ctaLabel: "Rezervasyon Yap",
    items: {
      single: {
        title: "1 Ders",
        description: "Esnek ve ihtiyaca yönelik",
        features: ["60 dakika birebir ders", "Esnek ders planlaması", "Özel ders içeriği"],
        unitPrice: "3.200 TL",
        totalPrice: "3.200 TL",
        discount: null,
      },
      package5: {
        title: "5 Derslik Paket",
        description: "Düzenli çalışmaya başlamak ve kısa vadeli konu hedeflerini takip etmek için esnek paket.",
        features: ["60 dakikalık 5 birebir ders", "%7 paket indirimi", "Düzenli konu takibi"],
        unitPrice: "3.000 TL",
        totalPrice: "15.000 TL",
        originalPrice: "16.000 TL",
        discount: "%7",
      },
      package10: {
        title: "10 Derslik Paket",
        description: "Sınav hazırlığı ve düzenli konu takibini birlikte yürüten dengeli paket.",
        features: ["60 dakikalık 10 birebir ders", "%15 paket indirimi", "Ders hakları ve akademik ilerleme takibi"],
        unitPrice: "2.700 TL",
        totalPrice: "27.000 TL",
        originalPrice: "32.000 TL",
        discount: "%15",
        badge: "En Çok Tercih Edilen",
      },
      package20: {
        title: "20 Derslik Paket",
        description: "Başarıya giden en popüler yol",
        features: ["60 dakikalık 20 birebir ders", "%20 paket indirimi", "Kapsamlı sınav hazırlığı"],
        unitPrice: "2.550 TL",
        totalPrice: "51.000 TL",
        originalPrice: "64.000 TL",
        discount: "%20",
      },
      package30: {
        title: "30 Derslik Paket",
        description: "Uzun vadeli maksimum avantaj",
        features: ["60 dakikalık 30 birebir ders", "%25 paket indirimi", "Sezon boyu kesintisiz destek"],
        unitPrice: "2.400 TL",
        totalPrice: "72.000 TL",
        originalPrice: "96.000 TL",
        discount: "%25",
        badge: "En Avantajlı Paket",
      },
    },
  },
  included: {
    eyebrow: "Ders özellikleri",
    title: "Tüm paketlerimizde sunulan standartlar.",
    intro: "Her ders paketi birebir akademik destek ve esnek çalışma imkânı sunar.",
    items: [
      { title: "60 Dakikalık Dersler", description: "Tüm derslerimiz 60 dakika olarak işlenmektedir." },
      { title: "Ön Ödemeli İndirim", description: "İndirimli paket ücretleri ön ödemeli şekildedir." },
      { title: "Haziran 2027 Fiyat Garantisi", description: "Ders ücretleri Haziran 2027 tarihine kadar sabittir." },
      { title: "Birebir Akademik Destek", description: "Esnek planlama ve kişiye özel birebir akademik destek." },
    ],
  },
  explanation: {
    eyebrow: "Süreç",
    title: "Nasıl başlarsınız?",
    intro: "İlk adım her zaman ücretsiz tanışma görüşmesidir.",
    steps: [
      { id: "conversation", title: "Ücretsiz Tanışma Görüşmesi", description: "Öğrencinin hedefleri ve ihtiyaç duyduğu ders alanı değerlendirilir." },
      { id: "assessment", title: "Paket Seçimi", description: "Öğrencinin temposuna ve sınav takvimine en uygun paket belirlenir." },
      { id: "proposal", title: "Ders Programı", description: "Ders saatleri planlanır ve birebir çalışma başlar." },
    ],
  },
  faq: {
    eyebrow: "Sık sorulan sorular",
    title: "Ücretler ve paketler hakkında.",
    items: [
      { question: "Dersler kaç dakika sürmektedir?", answer: "Derslerimiz 60 dakika olarak işlenmektedir." },
      { question: "Fiyatlar ne zamana kadar geçerlidir?", answer: "Ders ücretleri Haziran 2027 tarihine kadar sabittir." },
      { question: "Paket ödemeleri nasıl yapılır?", answer: "İndirimli paket ücretleri ön ödemeli şekildedir." },
      { question: "Tanışma görüşmesi ücretli mi?", answer: "Hayır. Ücretsiz tanışma görüşmesi her zaman tamamen ücretsizdir." },
    ],
  },
  cta: {
    eyebrow: "Görüşme planlayın",
    title: "Başlamaya hazır mısınız?",
    body: "Formu doldurun veya doğrudan bizimle iletişime geçin. İlk görüşme ücretsizdir.",
    primary: "Ücretsiz Tanışma Görüşmesi",
    secondary: "İletişime Geç",
  },
} satisfies PricingContent;
