import type { AboutContent } from "../about";

export const about: AboutContent = {
  metadata: {
    title: "About Us | Oriens Academy",
    description: "Meet Oriens Academy and its one-to-one preparation, academic assessment and university course support across 15 international exams.",
  },
  breadcrumb: { ariaLabel: "Breadcrumb", home: "Home", current: "About Us" },
  hero: {
    eyebrow: "About Us",
    title: "Meet Oriens Academy.",
    description: "Oriens Academy provides one-to-one preparation for 15 international exams alongside mathematics and physics-focused university course support. Our institutional approach is built on measurable progress, understanding how each exam works and creating the right route for each student's goals.",
    primaryCta: "Free Intro Call",
    secondaryCta: "Explore Exams",
    visualLabel: "Tutor Doğuhan — Mathematics & Physics Tutor",
    visualSteps: [
      "Robert College",
      "St. Joseph",
      "Liceo Italiano",
      "Üsküdar American Academy",
      "Galatasaray High School",
      "Saint Benoit",
      "Notre Dame de Sion",
      "Deutsche Schule Istanbul",
      "St. Georgs-Kolleg",
    ],
  },
  story: {
    eyebrow: "Our Approach",
    title: "Built on understanding how each exam actually works, not memorisation.",
    paragraphs: [
      "For over 10 years, we have worked one-on-one with students studying international curricula. We support students from leading international-curriculum schools such as Robert College, St. Joseph, Liceo Italiano, Üsküdar American Academy, Galatasaray High School, Saint Benoit, Notre Dame de Sion, Deutsche Schule Istanbul, and St. Georgs-Kolleg in reaching their academic goals.",
      "Every exam has its own language, scoring logic, and time pressure, so preparation is built around that exam specifically.",
    ],
    note: "Doğuhan — Mathematics & Physics Tutor & Founder of Oriens Academy",
  },
  principles: {
    eyebrow: "Principles",
    title: "Core principles guiding our approach.",
    intro: "Every lesson and preparation process is grounded in these five core principles.",
    items: [
      { id: "direction", title: "Exam Logic", description: "Focusing on understanding the logic behind questions, rather than memorisation." },
      { id: "individualisation", title: "1-on-1 Sessions", description: "Lessons tailored specifically to the student's level, pace, and topic gaps." },
      { id: "clarity", title: "Measurable Progress", description: "Regular timed mock exams and clear diagnostic assessments." },
      { id: "review", title: "Time Management", description: "Techniques and strategies for managing real time pressure during exams." },
      { id: "integrity", title: "Academic Trust", description: "10+ years of experience offering reliable guidance on the path to top universities." },
    ],
  },
  team: {
    eyebrow: "Leadership",
    title: "Our founding tutor",
    intro: "Mathematics & Physics tutor with 10+ years of experience.",
    members: [
      {
        id: "doguhan",
        name: "Doğuhan",
        role: "Mathematics & Physics Tutor / Founder",
        bio: "A Mathematics and Physics instructor with more than 10 years of one-to-one experience supporting students preparing for IB, AP, A-Level, SAT, ESAT, TMUA, MAT, STEP, PAT, TARA and IGCSE. His students include learners from international-curriculum schools such as Robert College, St. Joseph, Liceo Italiano, Üsküdar American Academy, Galatasaray High School, Saint Benoit, Notre Dame de Sion, Deutsche Schule Istanbul and St. Georgs-Kolleg. His approach is built on understanding the logic of each exam rather than rote memorisation.",
        credentials: [
          "Robert College",
          "St. Joseph",
          "Liceo Italiano",
          "Üsküdar American Academy",
          "Galatasaray High School",
          "Saint Benoit",
          "Notre Dame de Sion",
          "Deutsche Schule Istanbul",
          "St. Georgs-Kolleg",
        ],
      },
    ],
    fallbackTitle: "Direct 1-on-1 Support",
    fallbackBody: "All lessons are conducted directly under the guidance of our founding tutor, Doğuhan.",
    fallbackPoints: ["10+ Years Experience", "Target Schools & Foreign Curricula", "Tailored 1-on-1 Structure"],
  },
  brandMoment: {
    eyebrow: "Oriens Academy",
    title: "Let's chart your course.",
    body: "Creating the ideal study route for your target university and exam.",
    steps: ["Analysis", "Strategy", "Practice", "Results"],
  },
  outcomes: {
    eyebrow: "Our Schools",
    title: "Student communities we work with.",
    intro: "Our founder's 10+ years of teaching experience includes one-to-one work with students who attended these schools.",
    metrics: [],
    items: [
      { title: "Robert College", description: "Targeted coaching across IB and AP curricula." },
      { title: "St. Joseph", description: "French and international curriculum mathematics and physics support." },
      { title: "Liceo Italiano", description: "Italian High School curriculum and IMAT / international entrance prep." },
      { title: "Üsküdar American Academy", description: "1-on-1 support for IB HL/SL courses and SAT preparation." },
      { title: "Galatasaray High School", description: "French Baccalaureate and international examination support." },
      { title: "Saint Benoit", description: "French curriculum STEM reinforcement and exam readiness." },
      { title: "Notre Dame de Sion", description: "Advanced Mathematics and Physics exam preparation." },
      { title: "Deutsche Schule Istanbul", description: "Abitur and international STEM entrance test preparation." },
      { title: "St. Georgs-Kolleg", description: "Matura and advanced mathematics-physics coaching." },
    ],
    disclaimer: "School names identify institutions attended by our students and do not imply an official partnership or endorsement.",
  },
  trust: {
    eyebrow: "Contact Channels",
    title: "Get in touch.",
    intro: "Direct contact channels for questions and lesson bookings:",
    examLabel: "Contact",
    links: [
      { route: "contact", title: "WhatsApp", description: "Send an instant message via +90 544 293 90 40.", linkLabel: "Chat on WhatsApp" },
      { route: "contact", title: "Phone", description: "Call our corporate line at 0850 304 04 67.", linkLabel: "Call Now" },
      { route: "contact", title: "Email", description: "Write to info@oriens-academy.com for details.", linkLabel: "Send Email" },
      { route: "contact", title: "Instagram", description: "Follow our @oriens.academy profile.", linkLabel: "View Instagram" },
    ],
  },
  testimonials: {
    eyebrow: "What Students Say",
    title: "What Do Our Students Say?",
    items: [
      {
        id: "1",
        quote: "My son's IB Physics grade improved noticeably, and he now enjoys the subject.",
        author: "Ahu G.",
        role: "Parent · IB Physics",
      },
      {
        id: "2",
        quote: "My son's motivation and confidence in IB HL Maths and Physics grew noticeably.",
        author: "Yasemin T.",
        role: "Parent · IB HL Mathematics & Physics",
      },
      {
        id: "3",
        quote: "He teaches hard subjects in simple ways — I passed all my maths and physics exams with high grades.",
        author: "Ahmet S.",
        role: "Student · University Physics",
      },
      {
        id: "4",
        quote: "Delivered noticeable progress in a short time — a highly capable tutor.",
        author: "Ece A.",
        role: "Student · AYT Exam Prep",
      },
      {
        id: "5",
        quote: "Helped me get over my fear of geometry quickly, making the subject enjoyable with practical tips.",
        author: "Ada Elif A.",
        role: "Student · Secondary Mathematics & Physics",
      },
      {
        id: "6",
        quote: "Quickly identified our daughter's gaps and prepared her successfully for her written exam.",
        author: "Bülent I.",
        role: "Parent",
      },
    ],
  },
  cta: {
    eyebrow: "Introductory Call",
    title: "Ready to get started?",
    body: "Fill out the form or reach out directly. The first call is free.",
    primary: "Free Intro Call",
    secondary: "Contact Us",
  },
};
