import type { ExamDetailTextMap } from "../exams";

export const examDetailText: ExamDetailTextMap = {
  IB: {
    seoTitle: "IB Preparation & Academic Support | Oriens Academy",
    seoDescription: "Personalised academic support and study planning for IB Diploma Programme subjects, internal assessments and examinations.",
    overview: ["The International Baccalaureate Diploma Programme brings distinct academic fields together with the DP core in an integrated secondary programme.", "Preparation extends beyond final examinations: subject choices, conceptual depth, internal assessments and long-term study habits all need to work together."],
    preparationAreas: [{ title: "Subject foundations", description: "We identify gaps in mathematics and sciences and address them in line with the student's HL or SL scope." }, { title: "Assessment language", description: "We work systematically on command terms, solution presentation and markscheme expectations." }, { title: "IA planning", description: "We guide research-question, method and academic-communication decisions within clear ethical boundaries." }],
    oriensSupport: "We connect subject-specific tutoring with term planning, assessment timelines and regular progress review. The student's school programme and selected subject levels remain central to the route.",
    featuredFacts: [{ label: "Programme structure", value: "Subject groups and the DP core" }, { label: "Preparation focus", value: "Subjects, assessments and academic planning" }],
    faqs: [{ question: "Is IB support only for final examinations?", answer: "No. Subject content, internal assessments, study systems and examination preparation can be addressed together according to the student's needs." }, { question: "Does the plan differ for HL and SL students?", answer: "Yes. Subject level, the school's teaching sequence and the student's objectives directly shape the scope." }, { question: "How can Oriens support an IA?", answer: "We offer guidance on focus, method, structure and feedback while protecting academic integrity; we never write the student's work for them." }],
    cta: { title: "Let's plan your IB preparation route.", body: "We can review your subjects, upcoming assessments and goals, then build a sustainable academic plan.", primary: "Book a Consultation", secondary: "View All Exams" },
  },
  AP: {
    seoTitle: "AP Preparation & Tutoring | Oriens Academy",
    seoDescription: "Subject-focused preparation, question practice and individual support for AP Calculus, Statistics, Physics and Chemistry.",
    overview: ["Advanced Placement allows secondary students to take specific college-level courses and their associated assessments.", "Because each AP subject has its own content and assessment design, preparation should be built around the official framework for the selected course."],
    preparationAreas: [{ title: "Content map", description: "We map the units of the selected AP course against the student's current knowledge." }, { title: "Question formats", description: "We develop approaches for multiple-choice, free-response or subject-specific assessed work." }, { title: "Practice analysis", description: "Errors are classified by content, interpretation and time-management decisions." }],
    oriensSupport: "Oriens support is shaped around the chosen AP course. Instruction, controlled practice and feedback are planned alongside the student's school workload.",
    featuredFacts: [{ label: "Structure", value: "Subject-specific courses and assessments" }, { label: "Oriens focus", value: "Depth in mathematics and sciences" }],
    faqs: [{ question: "Can every AP subject use the same preparation plan?", answer: "No. Content and assessment vary, so the plan must reflect the selected AP subject." }, { question: "Can an AP result provide university credit?", answer: "Credit and placement policies are institution-specific. Students should check each target university's current policy directly." }, { question: "When should preparation begin?", answer: "Timing should be based on the student's foundation, school programme and selected subject rather than a universal start date." }],
    cta: { title: "Let's build a clear system for your AP course.", body: "We can assess your selected subject and current level, then define the content and question-practice route.", primary: "Book a Consultation", secondary: "View All Exams" },
  },
  IGCSE: {
    seoTitle: "IGCSE Preparation & Subject Support | Oriens Academy",
    seoDescription: "Curriculum tracking, concept consolidation and exam practice in Cambridge IGCSE mathematics and sciences.",
    overview: ["Cambridge IGCSE is an international secondary curriculum and qualification structure where schools select subject combinations.", "Assessment design varies across subjects, so preparation should follow the student's exact syllabus code and examination board."],
    preparationAreas: [{ title: "Syllabus tracking", description: "We match the syllabus specifications with the school's teaching progression." }, { title: "Conceptual foundation", description: "We emphasize principles and causal understanding over rote memorization in math and sciences." }, { title: "Past paper practice", description: "We use past papers and markschemes to sharpen technical answer precision." }],
    oriensSupport: "We provide structured support tailored to the student's IGCSE courses and school calendar, unifying instruction, homework review and exam practice.",
    featuredFacts: [{ label: "Structure", value: "Flexible subject combinations" }, { label: "Oriens scope", value: "Mathematics and science tutoring" }],
    faqs: [{ question: "Do all IGCSE subjects use the same format?", answer: "No. Written papers, coursework and practical exams vary by subject." }, { question: "Does Core vs Extended matter?", answer: "Yes. The choice between Core and Extended dictates the scope and target grade ceiling." }],
    cta: { title: "Build a strong foundation in your IGCSEs.", body: "Let us review your courses and school calendar to create a structured subject-support plan.", primary: "Book a Consultation", secondary: "View All Exams" },
  },
  "A-Level": {
    seoTitle: "A-Level Preparation & Private Tutoring | Oriens Academy",
    seoDescription: "In-depth academic support and exam technique for Cambridge, Edexcel and OxfordAQA A-Level mathematics and sciences.",
    overview: [
      "GCE Advanced Level (A-Level) is the primary subject-focused qualification required for undergraduate admissions in the UK and leading global universities.",
      "Achieving A* grades requires both deep conceptual mastery and precise examination technique aligned with official board markschemes.",
    ],
    preparationAreas: [
      { title: "Deep Content Mastery", description: "We master Pure Mathematics, Mechanics, Statistics, Physics and Chemistry modules from foundational concepts to advanced applications." },
      { title: "Markscheme Precision", description: "We train step-by-step working standards and mathematical communication expected by official examiners." },
      { title: "Timed Past-Paper Strategy", description: "We build speed, accuracy, and error-prevention under real examination time pressure." },
    ],
    oriensSupport: "We provide board-specific modular preparation (Cambridge CAIE, Pearson Edexcel, OxfordAQA), developing advanced problem-solving techniques for A* targets.",
    featuredFacts: [{ label: "Exam Boards", value: "Cambridge, Pearson Edexcel, OxfordAQA" }, { label: "Target", value: "A* and A grade attainment" }],
    faqs: [
      { question: "Can A-Level tutoring run parallel to school?", answer: "Yes. We coordinate with your school's timeline, providing topic reinforcement and pre-exam revision camps." },
      { question: "Do exam board specifications differ?", answer: "Yes. Formula sheets, question phrasing, and module structures vary between Cambridge and Edexcel; preparation is board-tailored." },
    ],
    cta: { title: "Elevate your A-Level preparation to A* standard.", body: "Review your subjects and target university requirements with us to establish an individualized roadmap.", primary: "Book a Consultation", secondary: "View All Exams" },
  },
  SAT: {
    seoTitle: "Digital SAT Preparation & Tutoring | Oriens Academy",
    seoDescription: "Personalised Digital SAT preparation, practice analysis and individual support across Reading and Writing and Math.",
    overview: ["The SAT is a digital assessment of reading, writing and mathematics skills that may be used as one element of undergraduate admissions.", "SAT policies vary by institution, so the decision to test should be considered alongside each target university's current requirements."],
    preparationAreas: [{ title: "Reading & Writing", description: "We work on evidence, context, conventions and rhetorical decisions in concise texts." }, { title: "Mathematics", description: "We strengthen the connection between concepts and application across algebra, problem solving, data analysis and advanced mathematics." }, { title: "Digital test strategy", description: "We build repeatable workflows for modules, digital tools and post-practice error review." }],
    oriensSupport: "After an initial diagnostic, content gaps, question approach and practice performance are combined in one plan. Progress is tracked through error patterns and solution quality, not only a total result.",
    featuredFacts: [{ label: "Assessment areas", value: "Reading & Writing · Math" }, { label: "Preparation model", value: "Diagnose · practise · analyse" }],
    faqs: [{ question: "Who should consider the SAT?", answer: "It may be relevant to undergraduate applicants whose target institutions require, accept or allow an SAT result. Current policies should always be checked." }, { question: "Is SAT preparation just completing practice tests?", answer: "No. Practice tests diagnose needs; lasting improvement requires content review, targeted questions and structured error analysis." }, { question: "Does Oriens offer individual SAT support?", answer: "Yes. Scope can be personalised around the student's level, objectives and available preparation time." }],
    cta: { title: "Let's plan your SAT preparation.", body: "We can review your current level and application goals, then create a measurable study route.", primary: "Book a Consultation", secondary: "View All Exams" },
  },
  ACT: {
    seoTitle: "ACT Preparation & Private Tutoring | Oriens Academy",
    seoDescription: "Speed, accuracy and strategic preparation for ACT English, Math, Reading and Science Reasoning.",
    overview: [
      "The American College Testing (ACT) is a standardized test used for undergraduate admissions in the United States and global universities.",
      "The exam is characterized by rapid pacing, data interpretation, and dedicated Science Reasoning sections.",
    ],
    preparationAreas: [
      { title: "Science Reasoning", description: "We master data representation, research summaries and conflicting viewpoints under strict time limits." },
      { title: "Math & Geometry", description: "We build fluency across intermediate algebra, plane geometry, and coordinate trigonometry." },
      { title: "Time & Pace Management", description: "We develop customized pacing strategies to maximize accurate attempts across all four sections." },
    ],
    oriensSupport: "We combine diagnostic testing with targeted speed drills and full-length proctored simulations to attain 34+ composite scores.",
    featuredFacts: [{ label: "Score Range", value: "1–36 Composite" }, { label: "Sections", value: "English, Math, Reading, Science (+Writing)" }],
    faqs: [
      { question: "Should I take the SAT or ACT?", answer: "A diagnostic baseline helps determine which test best fits your reading speed, math strengths, and scientific data fluency." },
      { question: "Does the Science section require advanced science recall?", answer: "No. It primarily tests scientific literacy, data interpretation, and logical analysis of experimental models." },
    ],
    cta: { title: "Reach top percentiles on the ACT.", body: "Take a diagnostic assessment and build a personalized ACT preparation roadmap.", primary: "Book a Consultation", secondary: "View All Exams" },
  },
  ESAT: {
    seoTitle: "ESAT Preparation & Academic Support | Oriens Academy",
    seoDescription: "Individual ESAT preparation across relevant mathematics and science modules, with applied problem-solving support.",
    overview: ["The Engineering and Science Admissions Test is a modular admissions assessment used by selected engineering and science programmes.", "Required modules can depend on the course, so candidates should confirm the current requirements on the relevant university course page before planning preparation."],
    preparationAreas: [{ title: "Core mathematics", description: "We practise applying mathematical knowledge in unfamiliar situations and selecting efficient methods." }, { title: "Course-relevant modules", description: "Physics, chemistry, biology or further mathematics work is selected from the student's actual application requirements." }, { title: "Technical problem solving", description: "We develop the ability to move from known science and mathematics to controlled application." }],
    oriensSupport: "We first establish the modules required by the target course, then create a content checklist and timed problem-solving plan aligned with the official specification.",
    featuredFacts: [{ label: "Assessment approach", value: "Applying science and mathematics" }, { label: "Module choice", value: "Depends on the target course" }],
    faqs: [{ question: "Which ESAT modules should I prepare for?", answer: "That depends on the course. The current requirements on the relevant university programme page must be the source of truth." }, { question: "Is school knowledge enough for ESAT?", answer: "The official test focuses on applying science and mathematics likely studied at school, but targeted practice is important for gaps and unfamiliar problems." }, { question: "Can Oriens coordinate science and mathematics modules?", answer: "Yes. The required module combination can be organised within one preparation timeline." }],
    cta: { title: "Let's clarify your ESAT module route.", body: "We can review your target course and academic foundation, then focus preparation on the right modules.", primary: "Book a Consultation", secondary: "View All Exams" },
  },
  TMUA: {
    seoTitle: "TMUA Preparation & Mathematics Tutoring | Oriens Academy",
    seoDescription: "Individual TMUA preparation for applying mathematical knowledge, mathematical reasoning and elementary logic.",
    overview: ["The Test of Mathematics for University Admission is used for applicants to mathematics and mathematics-related degrees to demonstrate application and reasoning skills.", "Requirements and use of results can vary by course and institution; current information should be confirmed on official university pages."],
    preparationAreas: [{ title: "Applying knowledge", description: "We use familiar mathematics flexibly in unfamiliar question settings." }, { title: "Mathematical reasoning", description: "We work on statements, necessary and sufficient conditions, and logical deduction." }, { title: "Solution efficiency", description: "We compare approaches and select controlled, economical routes to an answer." }],
    oriensSupport: "Content review is integrated with mathematical reasoning and timed problem sets. Errors are examined through assumptions and solution paths, not only final answers.",
    featuredFacts: [{ label: "Core axis", value: "Mathematical application and reasoning" }, { label: "Relevant degrees", value: "Mathematics-intensive undergraduate fields" }],
    faqs: [{ question: "Does TMUA test advanced content or reasoning?", answer: "It tests the application of defined mathematical content to unfamiliar contexts alongside mathematical logic; both must be practised together." }, { question: "Is syllabus review enough for TMUA?", answer: "Generally no. Content command needs to be paired with logic principles, unfamiliar problem designs and timed practice." }, { question: "Does my target university require TMUA?", answer: "Requirements vary. Always check the official course page for the relevant application cycle." }],
    cta: { title: "Let's map your TMUA mathematics route.", body: "We can review your foundation and problem-solving habits to create an individualized study system.", primary: "Book a Consultation", secondary: "View All Exams" },
  },
  TARA: {
    seoTitle: "Architecture Admissions (TARA / TEST-ARCHED) Preparation | Oriens Academy",
    seoDescription: "Spatial reasoning, 3D visualization, technical drawing logic and architectural history for Politecnico di Milano and international admissions.",
    overview: [
      "The Test di Ammissione ad Architettura (TEST-ARCHED / TARA) is the centralized admissions exam used for single-cycle Architecture degrees in Italy and European institutions.",
      "The test evaluates spatial visualization, orthographic projections, physical statics, mathematics, and the history of art and architecture.",
    ],
    preparationAreas: [
      { title: "Spatial Reasoning & 3D Perception", description: "We train geometric folding, cross-sections, perspective analysis, and axonometric views." },
      { title: "Physics & Structural Statics", description: "We master equilibrium of forces, structural principles, and basic mechanics in architectural contexts." },
      { title: "History of Architecture & Art", description: "We study pivotal movements, architects, historical styles, and monument analysis from antiquity to contemporary design." },
    ],
    oriensSupport: "We combine visual analysis with mathematical problem-solving discipline to exceed threshold scores for Politecnico di Milano, Politecnico di Torino, and global faculties.",
    featuredFacts: [{ label: "Administering Body", value: "CISIA / Italian Ministry of Universities (MUR)" }, { label: "Core Fields", value: "Spatial Reasoning, Mathematics, Physics, Architectural History" }],
    faqs: [
      { question: "Is the exam offered in English?", answer: "Yes. Italian universities offer the English version (TEST-ARCHED in English) for English-taught architecture programmes." },
      { question: "Is drawing ability tested directly?", answer: "The exam uses multiple-choice questions to test spatial logic and drawing comprehension; freehand drawing is not tested directly." },
    ],
    cta: { title: "Secure your place in top architecture schools.", body: "Develop your spatial reasoning and technical preparation with our expert tutors.", primary: "Book a Consultation", secondary: "View All Exams" },
  },
  UCAT: {
    seoTitle: "UCAT Preparation & Medical Admissions Tutoring | Oriens Academy",
    seoDescription: "Individual UCAT preparation for Verbal Reasoning, Decision Making, Quantitative Reasoning, Abstract Reasoning and SJT.",
    overview: [
      "The University Clinical Aptitude Test (UCAT, formerly UKCAT) is the primary admissions test for undergraduate medicine and dentistry in the UK and Australia.",
      "It evaluates cognitive aptitude, logical deductions, data fluency, and professional ethical judgment under intense time constraints.",
    ],
    preparationAreas: [
      { title: "Verbal & Quantitative Reasoning", description: "We develop rapid text-scanning and numerical decision strategies to preserve accuracy under speed." },
      { title: "Decision Making & Abstract Reasoning", description: "We master logical syllogisms, Venn deductions, and pattern recognition algorithms." },
      { title: "Situational Judgement (SJT)", description: "We align ethical instincts with General Medical Council (GMC) professional standards for Band 1 targets." },
    ],
    oriensSupport: "We provide subtest-specific workflows, keyboard shortcut techniques, timing pacing, and thorough question review without generic advice.",
    featuredFacts: [{ label: "Scoring", value: "Cognitive: 1200–3600 | SJT: Band 1–4" }, { label: "Scope", value: "UK, Australia, New Zealand Medicine & Dentistry" }],
    faqs: [
      { question: "When should I begin UCAT preparation?", answer: "Preparation is recommended 8–12 weeks prior to your test date during the summer testing window." },
      { question: "How does UCAT differ from legacy UKCAT?", answer: "UCAT expanded internationally in 2019; the format and standard remain the authoritative medical aptitude benchmark." },
    ],
    cta: { title: "Target top percentiles in the UCAT.", body: "Evaluate your baseline cognitive speed and build a dedicated medical admissions study plan.", primary: "Book a Consultation", secondary: "View All Exams" },
  },
  LNAT: {
    seoTitle: "LNAT Preparation & Law Admissions Tutoring | Oriens Academy",
    seoDescription: "Analytical reading, deductive logic and structured essay writing for Oxford, Cambridge, UCL, LSE and KCL law applicants.",
    overview: [
      "The National Admissions Test for Law (LNAT) is used by leading UK law faculties to evaluate critical thinking and analytical reasoning.",
      "The test does not require prior legal knowledge; it measures the candidate's ability to interpret complex arguments, detect bias, and write persuasive academic essays.",
    ],
    preparationAreas: [
      { title: "Critical Reading & Textual Analysis", description: "We dissect philosophical, sociological, and policy texts to uncover hidden premises." },
      { title: "Logical Deductions", description: "We apply deductive elimination to navigate subtle distractors in Section A." },
      { title: "LNAT Essay Writing", description: "We develop clear thesis formulation, counter-argument balance, and evidence-driven prose in Section B." },
    ],
    oriensSupport: "We train deep analytical reasoning and provide line-by-line essay feedback aligned with Oxford and Cambridge admissions criteria.",
    featuredFacts: [{ label: "Test Structure", value: "Section A: 42 MCQs | Section B: 1 Essay" }, { label: "Target Law Schools", value: "Oxford, Cambridge, UCL, LSE, KCL, Bristol, Durham" }],
    faqs: [
      { question: "Do I need legal knowledge for LNAT?", answer: "No. The exam assesses logical reasoning, critical interpretation, and written communication in English." },
      { question: "How is Section B evaluated?", answer: "The essay is forwarded directly to admissions tutors at your chosen universities for qualitative review." },
    ],
    cta: { title: "Prepare for competitive law school admissions.", body: "Review your reading and essay writing baseline with specialized LNAT instructors.", primary: "Book a Consultation", secondary: "View All Exams" },
  },
  IMAT: {
    seoTitle: "IMAT Preparation & Italian Medical Admissions | Oriens Academy",
    seoDescription: "Comprehensive scientific preparation in biology, chemistry, physics, math and logical reasoning for English-taught medicine in Italy.",
    overview: ["The International Medical Admissions Test (IMAT) is the national entrance exam for English-taught Medicine and Surgery programmes in Italian public universities.", "The broad scientific syllabus and negative marking scheme necessitate high conceptual accuracy and disciplined question selection."],
    preparationAreas: [
      { title: "Biology & Chemistry Depth", description: "We cover cell biology, bioenergetics, genetics, and organic chemistry aligned with IMAT question models." },
      { title: "Physics & Mathematics", description: "We master quantitative problem-solving without calculator support." },
      { title: "Logical Reasoning", description: "We build speed in syllogisms, argument analysis, and numerical problem solving." },
    ],
    oriensSupport: "We integrate comprehensive syllabus coverage with past-paper workshops and negative-marking simulation drills for top Italian public faculties.",
    featuredFacts: [{ label: "Max Score", value: "90 Points (+1.5 correct, -0.4 incorrect)" }, { label: "Authority", value: "Italian Ministry of University and Research (MUR)" }],
    faqs: [
      { question: "Is Italian language proficiency required for IMAT?", answer: "No. The exam and entire degree curriculum are conducted in English." },
      { question: "Which universities use IMAT?", answer: "University of Milan, Sapienza Rome, Bologna, Pavia, Padova, Tor Vergata, and other public medical schools." },
    ],
    cta: { title: "Plan your medical education in Italy.", body: "Evaluate your science baseline and start your personalized IMAT preparation plan.", primary: "Book a Consultation", secondary: "View All Exams" },
  },
  GAMSAT: {
    seoTitle: "GAMSAT Preparation & Graduate Entry Medicine | Oriens Academy",
    seoDescription: "Individual preparation across Section I (Humanities), Section II (Written Communication), and Section III (Sciences) for GEM.",
    overview: [
      "The Graduate Medical School Admissions Test (GAMSAT) is used for admission to graduate-entry medicine and dentistry in the UK, Ireland, and Australia.",
      "It tests reasoning in humanities, social sciences, written communication, and biological and physical sciences at university level.",
    ],
    preparationAreas: [
      { title: "Section I (Humanities Reasoning)", description: "We analyse literary, philosophical, and social science texts under strict time constraints." },
      { title: "Section II (Written Communication)", description: "We craft thoughtful, well-argued essays across diverse socio-cultural and philosophical prompts." },
      { title: "Section III (Physical & Biological Sciences)", description: "We develop problem-solving fluency in organic chemistry, biochemistry, physiology, and physics." },
    ],
    oriensSupport: "We offer balanced study timelines, extensive essay marking, and scientific reasoning mentorship for candidates with and without STEM backgrounds.",
    featuredFacts: [{ label: "Testing Body", value: "ACER (Australian Council for Educational Research)" }, { label: "Scope", value: "Graduate Entry Medicine (UK, Ireland, Australia)" }],
    faqs: [
      { question: "Can non-science graduates take GAMSAT?", answer: "Yes. GAMSAT assesses data interpretation and reasoning rather than pure recall; candidates from all academic backgrounds prepare successfully." },
    ],
    cta: { title: "Take your next step toward graduate-entry medicine.", body: "Review your skills profile with our tutors to structure a comprehensive GAMSAT roadmap.", primary: "Book a Consultation", secondary: "View All Exams" },
  },
  MCAT: {
    seoTitle: "MCAT Preparation & US/Canada Medical Admissions | Oriens Academy",
    seoDescription: "In-depth preparation for Chemical/Physical, CARS, Biological, and Psychological Foundations for North American medical schools.",
    overview: [
      "The Medical College Admission Test (MCAT) is administered by the AAMC and is the standardized benchmark for medical school admissions in the United States and Canada.",
      "It evaluates foundational concepts in natural and behavioral sciences alongside critical reasoning in complex biomedical passages.",
    ],
    preparationAreas: [
      { title: "Biological & Biochemical Foundations", description: "We master metabolic pathways, molecular genetics, and organ-system integration." },
      { title: "Chemical & Physical Foundations", description: "We solve complex thermodynamics, organic reaction mechanisms, and biophysics problems." },
      { title: "CARS (Critical Analysis & Reasoning)", description: "We dissect author arguments, tone, and philosophical rhetoric in non-science passages." },
      { title: "Psychological & Social Foundations", description: "We cover cognitive psychology, sociological frameworks, and behavioral biology." },
    ],
    oriensSupport: "We provide content review, AAMC question-pack analysis, and full-length testing stamina for 515+ score targets.",
    featuredFacts: [{ label: "Score Range", value: "472–528 Total Score" }, { label: "Application Portals", value: "AMCAS, AACOMAS, OMSAS" }],
    faqs: [
      { question: "What is the recommended MCAT study timeline?", answer: "Most applicants require 4–6 months of structured study (300–500 total hours) with regular full-length testing." },
      { question: "How can I improve CARS performance?", answer: "CARS requires active passage mapping, identifying argument assumptions, and avoiding extreme answer choices." },
    ],
    cta: { title: "Aim for top percentiles on the MCAT.", body: "Take a diagnostic baseline and establish your personalized 515+ study schedule.", primary: "Book a Consultation", secondary: "View All Exams" },
  },
  LSAT: {
    seoTitle: "LSAT Preparation & Top JD Admissions | Oriens Academy",
    seoDescription: "Master Logical Reasoning and Reading Comprehension with rigorous analytical frameworks for T14 law school admissions.",
    overview: [
      "The Law School Admission Test (LSAT) is administered by the LSAC and serves as the primary quantitative admissions criterion for JD programs in the US and Canada.",
      "It assesses rigorous formal logic, argument critique, deduction, and complex legal/philosophical reading comprehension.",
    ],
    preparationAreas: [
      { title: "Logical Reasoning", description: "We master assumption identification, flaw analysis, strengthen/weaken mechanics, and parallel reasoning patterns." },
      { title: "Reading Comprehension", description: "We map comparative passages, rhetorical structure, and author viewpoint in dense academic texts." },
      { title: "Pacing & Precision", description: "We eliminate trap answer choices under section time constraints to achieve 170+ percentile targets." },
    ],
    oriensSupport: "We replace intuitive guessing with formal logical precision, guiding students toward 99th-percentile scores.",
    featuredFacts: [{ label: "Score Scale", value: "120–180 Scaled Score" }, { label: "Target", value: "T14 and leading US / Canadian Law Schools (JD)" }],
    faqs: [
      { question: "Is prior legal knowledge tested?", answer: "No. The exam strictly evaluates abstract logical reasoning, analytical reading, and critical inference." },
      { question: "What score is required for T14 law schools?", answer: "Top-tier law schools typically have median scores in the 170–174 range." },
    ],
    cta: { title: "Target a 170+ score for premier law schools.", body: "Test your logical reasoning baseline and build your targeted LSAT roadmap with our mentors.", primary: "Book a Consultation", secondary: "View All Exams" },
  },
  GRE: {
    seoTitle: "GRE Preparation & Individual Tutoring | Oriens Academy",
    seoDescription: "Diagnostic-led preparation across Quantitative Reasoning, Verbal Reasoning and Analytical Writing for graduate admissions.",
    overview: ["The GRE General Test assesses verbal reasoning, quantitative reasoning, critical thinking and analytical writing for graduate school admissions.", "Which programmes require or accept GRE scores varies, so applicants should check current requirements with their target institutions."],
    preparationAreas: [{ title: "Quantitative Reasoning", description: "We practise interpreting numerical data, mathematical modeling and applying core mathematical principles." }, { title: "Verbal Reasoning", description: "We work on analyzing academic texts, drawing inferences and evaluating vocabulary relationships." }, { title: "Analytical Writing", description: "We build the ability to articulate complex ideas with clear thesis statements and structured support." }],
    oriensSupport: "Priorities are established from baseline diagnostic performance. Quantitative, verbal and writing workloads are balanced according to the target programme.",
    featuredFacts: [{ label: "Skill areas", value: "Verbal · Quantitative · Analytical Writing" }, { label: "Context", value: "Graduate school applications" }],
    faqs: [{ question: "Is the GRE required for all graduate programmes?", answer: "No. Policies vary by institution and department; check current requirements directly." }, { question: "Does Quantitative require advanced mathematics?", answer: "It focuses on understanding and applying arithmetic, algebra, geometry and data interpretation." }],
    cta: { title: "Let's plan your GRE preparation for graduate school.", body: "We can build a balanced, measurable study route across quantitative, verbal and writing skills.", primary: "Book a Consultation", secondary: "View All Exams" },
  },
  GMAT: {
    seoTitle: "GMAT Focus Preparation & Private Tutoring | Oriens Academy",
    seoDescription: "Personalised preparation across Quantitative Reasoning, Verbal Reasoning and Data Insights for business school admissions.",
    overview: ["The GMAT Focus Edition assesses quantitative, verbal and data-driven reasoning in the context of graduate business education.", "Requirements vary across business schools, so candidates should confirm current policies with their target MBA and master's programmes."],
    preparationAreas: [{ title: "Quantitative Reasoning", description: "We connect arithmetic and algebra principles with problem-solving efficiency." }, { title: "Verbal Reasoning", description: "We develop critical reasoning, argument evaluation and reading comprehension." }, { title: "Data Insights", description: "We practise analyzing tables, multi-source data and graphics to make strategic deductions." }],
    oriensSupport: "We address all three sections within an integrated diagnostic system, tracking data literacy, timing efficiency and error patterns.",
    featuredFacts: [{ label: "Section axes", value: "Quantitative · Verbal · Data Insights" }, { label: "Target", value: "Graduate business and MBA programmes" }],
    faqs: [{ question: "Is GMAT only for MBA programmes?", answer: "No. It is also used for specialised master's degrees in finance, management, and business analytics." }, { question: "How should I prepare for Data Insights?", answer: "Through integrated practice combining tables, graphs, multi-source texts and quantitative reasoning." }],
    cta: { title: "Align your GMAT preparation with your business school goals.", body: "Assess your skill profile and create a balanced quantitative, verbal and data study plan.", primary: "Book a Consultation", secondary: "View All Exams" },
  },
  OMPT: {
    seoTitle: "OMPT Preparation & Mathematics Tutoring | Oriens Academy",
    seoDescription: "Targeted concept review and problem-solving support for programme-specific OMPT mathematics tests.",
    overview: ["The Online Mathematics Placement Test (OMPT) is an online admissions test family used by European universities to verify mathematics competency.", "Because different OMPT variants cover different syllabi, preparation must be organized after confirming the exact variant required by the university."],
    preparationAreas: [{ title: "Variant confirmation", description: "We confirm the specific OMPT test variant (OMPT-A through F) required by your target course." }, { title: "Concept consolidation", description: "We review algebra, functions, calculus, trigonometry, and statistics according to syllabus needs." }, { title: "Digital problem solving", description: "We practice computer-based formula input and clean digital problem-solving workflows." }],
    oriensSupport: "Preparation begins with your exact OMPT test variant and required passing score, tailoring practice and feedback to your target degree.",
    featuredFacts: [{ label: "Test family", value: "Programme-specific mathematics variants (A–F)" }, { label: "First step", value: "Confirming your required test variant" }],
    faqs: [{ question: "Which OMPT test should I take?", answer: "Your target university or programme specifies the required variant (e.g., OMPT-A for Economics, OMPT-B for Engineering)." }, { question: "Can Oriens focus only on my weak topics?", answer: "Yes. Diagnostic review allows us to focus tutoring directly on your priority areas." }],
    cta: { title: "Prepare for your required OMPT variant.", body: "Let us review your test variant and mathematics level to build a focused study plan.", primary: "Book a Consultation", secondary: "View All Exams" },
  },
};
