import type { PricingContent } from "../pricing";

export const pricing = {
  metadata: {
    title: "Fees & Packages | Oriens Academy",
    description: "More lessons, better value. Free initial consultation and 1, 5, 10, 20, 30 lesson package options.",
  },
  breadcrumb: { ariaLabel: "Breadcrumb", home: "Home", current: "Fees" },
  hero: {
    eyebrow: "Flexible Lesson Packages",
    title: "Choose the study plan that fits your goals.",
    description: "From individual lessons to long-term preparation, choose a study structure aligned with your academic goals.",
    primaryCta: "Choose a Package, Book Now",
    secondaryCta: "Free Intro Call",
    indexLabel: "5 lesson package options",
  },
  packages: {
    eyebrow: "Packages",
    title: "More lessons, better per-lesson value.",
    intro: "Transparent and flexible lesson packages with a price guarantee until June 2027.",
    featuredLabel: "Most Popular",
    activeLabel: "Active package",
    priceSourceNote: "Programme content and lesson planning are shaped around each student’s goals.",
    customPrice: "Get in Touch",
    billingLabels: { session: "/ lesson", month: "package", custom: "Custom" },
    formatStartingPrice: (amount) => `${amount} TRY`,
    ctaLabel: "Book Now",
    items: {
      single: {
        title: "Single Lesson",
        description: "Flexible support based on your needs",
        features: ["60-minute 1:1 lesson", "Flexible scheduling", "Custom lesson content"],
        unitPrice: "3,200 TRY",
        totalPrice: "3,200 TRY",
        discount: null,
      },
      package5: {
        title: "5-Lesson Package",
        description: "A flexible package for starting structured study and tracking short-term topic goals.",
        features: ["5 60-minute 1:1 lessons", "7% package discount", "Regular topic review"],
        unitPrice: "3,000 TRY",
        totalPrice: "15,000 TRY",
        originalPrice: "16,000 TRY",
        discount: "7%",
      },
      package10: {
        title: "10-Lesson Package",
        description: "A balanced package combining exam preparation, topic tracking and regular progress review.",
        features: ["10 60-minute 1:1 lessons", "15% package discount", "Exam and homework tracking"],
        unitPrice: "2,700 TRY",
        totalPrice: "27,000 TRY",
        originalPrice: "32,000 TRY",
        discount: "15%",
        badge: "Most Popular",
      },
      package20: {
        title: "20-Lesson Package",
        description: "A structured path for ongoing progress",
        features: ["20 60-minute 1:1 lessons", "20% package discount", "Comprehensive exam preparation"],
        unitPrice: "2,550 TRY",
        totalPrice: "51,000 TRY",
        originalPrice: "64,000 TRY",
        discount: "20%",
      },
      package30: {
        title: "30-Lesson Package",
        description: "Maximum long-term value",
        features: ["30 60-minute 1:1 lessons", "25% package discount", "Season-long academic support"],
        unitPrice: "2,400 TRY",
        totalPrice: "72,000 TRY",
        originalPrice: "96,000 TRY",
        discount: "25%",
        badge: "Best Value",
      },
    },
  },
  included: {
    eyebrow: "Lesson Features",
    title: "Standards across all packages.",
    intro: "Every lesson package offers 1-on-1 academic support and flexible scheduling.",
    items: [
      { title: "60-Minute Lessons", description: "Our lessons run for 60 minutes." },
      { title: "Prepaid Discount", description: "Discounted package fees are prepaid." },
      { title: "June 2027 Price Guarantee", description: "Fees are fixed until June 2027." },
      { title: "1-on-1 Academic Support", description: "Flexible scheduling and tailored academic guidance." },
    ],
  },
  explanation: {
    eyebrow: "Process",
    title: "How to get started?",
    intro: "The first step is always a free introductory call.",
    steps: [
      { id: "conversation", title: "Free Intro Call", description: "We assess the student's goals and subject needs." },
      { id: "assessment", title: "Select a Package", description: "We determine the best package for the student's pace and exam schedule." },
      { id: "proposal", title: "Schedule Lessons", description: "Lesson times are set and 1-on-1 work begins." },
    ],
  },
  faq: {
    eyebrow: "Frequently Asked Questions",
    title: "About fees and packages.",
    items: [
      { question: "How long are the lessons?", answer: "Our lessons run for 60 minutes." },
      { question: "How long are these fees valid for?", answer: "Fees are fixed until June 2027." },
      { question: "How are package payments made?", answer: "Discounted package fees are prepaid." },
      { question: "Is the introductory call free?", answer: "Yes, the intro call is always completely free." },
    ],
  },
  cta: {
    eyebrow: "Book a Call",
    title: "Ready to get started?",
    body: "Fill out the form or reach out directly. The first call is free.",
    primary: "Free Intro Call",
    secondary: "Contact Us",
  },
} satisfies PricingContent;
