export const adminLessonCopy = {
  tr: {
    pastAction: "Geçmiş Ders Ekle",
    pastHeading: "Geçmiş / Plansız Tamamlanan Ders",
    learner: "Öğrenci",
    date: "Tarih",
    startTime: "Başlangıç Saati",
    duration: "Süre (Dakika)",
    title: "Ders Başlığı",
    subject: "Konu / Alan",
    defaultTitle: "Birebir Ders",
    defaultSubject: "Genel Ders",
    titlePlaceholder: "Birebir Ders",
    subjectPlaceholder: "Ders konusu",
    note: "Not (isteğe bağlı)",
    package: "Ders Hakkının Kullanılacağı Paket",
    fifo: "En eski aktif paketi otomatik kullan (FIFO)",
    cancel: "Vazgeç",
    save: "Dersi Tamamlandı Olarak Kaydet",
    saving: "Kaydediliyor…",
    success: "Geçmiş ders kaydedildi ve tam olarak 1 ders hakkı kullanıldı.",
    failure: "Ders kaydedilemedi.",
    remaining: "kalan",
    accountEmail: "Bilgilendirme e-postası hesap sahibine outbox üzerinden gönderilecektir.",
  },
  en: {
    pastAction: "Add Past Lesson",
    pastHeading: "Past / Unscheduled Completed Lesson",
    learner: "Learner",
    date: "Date",
    startTime: "Start Time",
    duration: "Duration (Minutes)",
    title: "Lesson Title",
    subject: "Subject",
    defaultTitle: "1-on-1 Lesson",
    defaultSubject: "General Lesson",
    titlePlaceholder: "1-on-1 Lesson",
    subjectPlaceholder: "Lesson subject",
    note: "Note (optional)",
    package: "Package to Consume",
    fifo: "Automatically use the oldest active package (FIFO)",
    cancel: "Cancel",
    save: "Record Completed Lesson",
    saving: "Saving…",
    success: "The past lesson was recorded and exactly 1 lesson right was used.",
    failure: "The lesson could not be recorded.",
    remaining: "remaining",
    accountEmail: "The completion email will be sent to the account holder through the outbox.",
  },
} as const;
