export const canonicalExamCodes = [
  "IB", "AP", "IGCSE", "A-Level", "SAT", "ACT",
  "ESAT", "TMUA", "TARA", "UCAT", "LNAT", "IMAT",
  "GAMSAT", "MCAT", "LSAT", "GRE", "GMAT", "OMPT",
] as const;

export type CanonicalExamCode = (typeof canonicalExamCodes)[number];
export type ExamEntityKind = "programme_or_qualification" | "admission_test";
export type CustomerExamGroup = 1 | 2;

export type CanonicalExam = {
  code: CanonicalExamCode;
  slug: string;
  canonicalName: string;
  displayNameTr: string;
  displayNameEn: string;
  entityKind: ExamEntityKind;
  customerGroup: CustomerExamGroup;
  purpose: string;
  officialBody: string;
  officialUrl: string;
  shortDescriptionTr: string;
  shortDescriptionEn: string;
  active: true;
  supportedPublic: true;
  displayOrder: number;
  currentSpecVersion: string;
  verifiedAt: string;
  aliases: readonly { alias: string; type: "acronym" | "legacy" | "variant"; priority: number }[];
};

const verifiedAt = "2026-08-30";
const common = { active: true, supportedPublic: true, verifiedAt } as const;

/**
 * Reviewed, locale-aware build snapshot of the canonical database catalog.
 * Static-export routes and UI adapters are generated from this artifact. The
 * database migration carries the same records and the validation suite blocks
 * drift between the two representations.
 */
export const canonicalExams: readonly CanonicalExam[] = [
  { ...common, code: "IB", slug: "ib", canonicalName: "International Baccalaureate Diploma Programme (DP)", displayNameTr: "International Baccalaureate (IB)", displayNameEn: "International Baccalaureate (IB)", entityKind: "programme_or_qualification", customerGroup: 1, purpose: "International secondary curriculum and diploma", officialBody: "International Baccalaureate Organization", officialUrl: "https://www.ibo.org/programmes/diploma-programme/", shortDescriptionTr: "IB Diploma Programme için disiplinler arası akademik hazırlık.", shortDescriptionEn: "Interdisciplinary academic preparation for the IB Diploma Programme.", displayOrder: 1, currentSpecVersion: "DP current at 2026-08-30", aliases: [{ alias: "IBDP", type: "acronym", priority: 90 }, { alias: "IB Diploma", type: "variant", priority: 85 }, { alias: "International Baccalaureate", type: "variant", priority: 95 }] },
  { ...common, code: "AP", slug: "ap", canonicalName: "Advanced Placement Program / AP Exams", displayNameTr: "Advanced Placement (AP)", displayNameEn: "Advanced Placement (AP)", entityKind: "programme_or_qualification", customerGroup: 1, purpose: "Advanced secondary curriculum and subject examinations", officialBody: "College Board", officialUrl: "https://apstudents.collegeboard.org/", shortDescriptionTr: "AP dersleri ve konu bazlı sınavlar için akademik hazırlık.", shortDescriptionEn: "Academic preparation for AP courses and subject examinations.", displayOrder: 2, currentSpecVersion: "AP current at 2026-08-30", aliases: [{ alias: "Advanced Placement", type: "variant", priority: 95 }, { alias: "AP Exams", type: "variant", priority: 85 }] },
  { ...common, code: "IGCSE", slug: "igcse", canonicalName: "International General Certificate of Secondary Education", displayNameTr: "IGCSE", displayNameEn: "IGCSE", entityKind: "programme_or_qualification", customerGroup: 1, purpose: "International secondary qualification", officialBody: "Multiple awarding organisations, including Cambridge International Education and Pearson Edexcel", officialUrl: "https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-upper-secondary/cambridge-igcse/", shortDescriptionTr: "Farklı sağlayıcıların IGCSE dersleri için konu ve sınav hazırlığı.", shortDescriptionEn: "Subject and exam preparation for provider-specific IGCSE qualifications.", displayOrder: 3, currentSpecVersion: "Provider-specific specifications current at 2026-08-30", aliases: [{ alias: "International GCSE", type: "variant", priority: 90 }, { alias: "Cambridge IGCSE", type: "variant", priority: 85 }, { alias: "Edexcel International GCSE", type: "variant", priority: 80 }] },
  { ...common, code: "A-Level", slug: "a-level", canonicalName: "General Certificate of Education Advanced Level (GCE A level)", displayNameTr: "A-Level", displayNameEn: "A-Level", entityKind: "programme_or_qualification", customerGroup: 1, purpose: "Advanced secondary qualification and curriculum", officialBody: "Multiple awarding organisations and regulators", officialUrl: "https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-advanced/cambridge-international-as-and-a-levels/", shortDescriptionTr: "A-Level ve sağlayıcıya özgü uluslararası varyantlar için hazırlık.", shortDescriptionEn: "Preparation for A levels and provider-specific international variants.", displayOrder: 4, currentSpecVersion: "Provider-specific specifications current at 2026-08-30", aliases: [{ alias: "A Level", type: "variant", priority: 95 }, { alias: "A-LEVEL", type: "variant", priority: 95 }, { alias: "ALEVEL", type: "legacy", priority: 90 }, { alias: "GCE A level", type: "variant", priority: 85 }] },
  { ...common, code: "SAT", slug: "sat", canonicalName: "SAT", displayNameTr: "SAT", displayNameEn: "SAT", entityKind: "admission_test", customerGroup: 1, purpose: "Undergraduate university admission test", officialBody: "College Board", officialUrl: "https://satsuite.collegeboard.org/sat", shortDescriptionTr: "Dijital SAT için Reading and Writing ile Math hazırlığı.", shortDescriptionEn: "Reading and Writing and Math preparation for the digital SAT.", displayOrder: 5, currentSpecVersion: "Digital SAT current at 2026-08-30", aliases: [{ alias: "SAT Reasoning Test", type: "legacy", priority: 70 }, { alias: "Digital SAT", type: "variant", priority: 90 }] },
  { ...common, code: "ACT", slug: "act", canonicalName: "ACT", displayNameTr: "ACT", displayNameEn: "ACT", entityKind: "admission_test", customerGroup: 1, purpose: "Undergraduate university admission test", officialBody: "ACT, Inc.", officialUrl: "https://www.act.org/content/act/en/products-and-services/the-act.html", shortDescriptionTr: "ACT bölümleri için hız, doğruluk ve akademik muhakeme hazırlığı.", shortDescriptionEn: "Speed, accuracy and academic reasoning preparation for the ACT.", displayOrder: 6, currentSpecVersion: "ACT current at 2026-08-30", aliases: [{ alias: "American College Testing", type: "legacy", priority: 65 }, { alias: "the ACT test", type: "variant", priority: 85 }] },
  { ...common, code: "ESAT", slug: "esat", canonicalName: "Engineering and Science Admissions Test", displayNameTr: "ESAT", displayNameEn: "ESAT", entityKind: "admission_test", customerGroup: 2, purpose: "Programme-specific engineering and science admission test", officialBody: "UAT-UK; delivered by Pearson VUE", officialUrl: "https://esat-tmua.ac.uk/about-the-tests/esat/", shortDescriptionTr: "Programa göre seçilen ESAT modülleri için muhakeme odaklı hazırlık.", shortDescriptionEn: "Reasoning-led preparation for programme-specific ESAT modules.", displayOrder: 7, currentSpecVersion: "UAT-UK current at 2026-08-30", aliases: [] },
  { ...common, code: "TMUA", slug: "tmua", canonicalName: "Test of Mathematics for University Admission", displayNameTr: "TMUA", displayNameEn: "TMUA", entityKind: "admission_test", customerGroup: 2, purpose: "Programme-specific mathematics admission test", officialBody: "UAT-UK; delivered by Pearson VUE", officialUrl: "https://esat-tmua.ac.uk/about-the-tests/tmua/", shortDescriptionTr: "TMUA için ileri matematiksel düşünme ve muhakeme hazırlığı.", shortDescriptionEn: "Advanced mathematical thinking and reasoning preparation for TMUA.", displayOrder: 8, currentSpecVersion: "UAT-UK current at 2026-08-30", aliases: [] },
  { ...common, code: "TARA", slug: "tara", canonicalName: "Test of Academic Reasoning for Admissions", displayNameTr: "TARA", displayNameEn: "TARA", entityKind: "admission_test", customerGroup: 2, purpose: "Programme-specific academic reasoning admission test", officialBody: "UAT-UK; delivered by Pearson VUE", officialUrl: "https://esat-tmua.ac.uk/about-the-tests/tara/", shortDescriptionTr: "Critical Thinking, Problem Solving ve Writing Task odaklı TARA hazırlığı.", shortDescriptionEn: "TARA preparation across Critical Thinking, Problem Solving and the Writing Task.", displayOrder: 9, currentSpecVersion: "UAT-UK format first offered October 2025", aliases: [{ alias: "Test of Academic Reasoning for Admissions", type: "variant", priority: 95 }] },
  { ...common, code: "UCAT", slug: "ucat", canonicalName: "University Clinical Aptitude Test", displayNameTr: "UCAT", displayNameEn: "UCAT", entityKind: "admission_test", customerGroup: 2, purpose: "Medicine and dentistry admission test", officialBody: "UCAT Consortium; delivered by Pearson VUE", officialUrl: "https://www.ucat.ac.uk/", shortDescriptionTr: "UCAT'ın güncel dört alt testi için zaman yönetimi ve muhakeme hazırlığı.", shortDescriptionEn: "Timing and reasoning preparation for the four current UCAT subtests.", displayOrder: 10, currentSpecVersion: "Four-subtest format current at 2026-08-30", aliases: [{ alias: "UKCAT", type: "legacy", priority: 100 }] },
  { ...common, code: "LNAT", slug: "lnat", canonicalName: "National Admissions Test for Law", displayNameTr: "LNAT", displayNameEn: "LNAT", entityKind: "admission_test", customerGroup: 2, purpose: "Programme-specific law admission test", officialBody: "LNAT Consortium; delivered by Pearson VUE", officialUrl: "https://lnat.ac.uk/", shortDescriptionTr: "LNAT çoktan seçmeli bölüm ve essay için eleştirel okuma hazırlığı.", shortDescriptionEn: "Critical reading preparation for the LNAT multiple-choice section and essay.", displayOrder: 11, currentSpecVersion: "LNAT current at 2026-08-30", aliases: [] },
  { ...common, code: "IMAT", slug: "imat", canonicalName: "International Medical Admissions Test (IMAT)", displayNameTr: "IMAT", displayNameEn: "IMAT", entityKind: "admission_test", customerGroup: 2, purpose: "Cycle-specific admission to English-taught medical programmes in Italy", officialBody: "Italian Ministry of University and Research (MUR)", officialUrl: "https://www.mur.gov.it/it/atti-e-normativa/decreto-ministeriale-n-1005-del-06-08-2026", shortDescriptionTr: "İtalya'daki İngilizce tıp programları için döngüye özgü IMAT hazırlığı.", shortDescriptionEn: "Cycle-aware IMAT preparation for English-taught medical programmes in Italy.", displayOrder: 12, currentSpecVersion: "2026 MUR cycle", aliases: [{ alias: "International Medical Admissions Test", type: "variant", priority: 90 }] },
  { ...common, code: "GAMSAT", slug: "gamsat", canonicalName: "GAMSAT", displayNameTr: "GAMSAT", displayNameEn: "GAMSAT", entityKind: "admission_test", customerGroup: 2, purpose: "Graduate-entry health and medical admission test", officialBody: "Australian Council for Educational Research (ACER)", officialUrl: "https://gamsat.acer.org/", shortDescriptionTr: "GAMSAT için beşerî bilimler, yazılı iletişim ve bilimsel muhakeme hazırlığı.", shortDescriptionEn: "Humanities, written communication and scientific reasoning preparation for GAMSAT.", displayOrder: 13, currentSpecVersion: "ACER current at 2026-08-30", aliases: [{ alias: "Graduate Medical School Admissions Test", type: "legacy", priority: 75 }] },
  { ...common, code: "MCAT", slug: "mcat", canonicalName: "Medical College Admission Test", displayNameTr: "MCAT", displayNameEn: "MCAT", entityKind: "admission_test", customerGroup: 2, purpose: "Medical school admission test", officialBody: "Association of American Medical Colleges (AAMC)", officialUrl: "https://students-residents.aamc.org/about-mcat-exam/about-mcat-exam", shortDescriptionTr: "MCAT için bilimsel bilgi, veri yorumlama ve eleştirel analiz hazırlığı.", shortDescriptionEn: "Scientific knowledge, data interpretation and critical analysis preparation for MCAT.", displayOrder: 14, currentSpecVersion: "AAMC current at 2026-08-30", aliases: [] },
  { ...common, code: "LSAT", slug: "lsat", canonicalName: "Law School Admission Test", displayNameTr: "LSAT", displayNameEn: "LSAT", entityKind: "admission_test", customerGroup: 2, purpose: "Law school admission test", officialBody: "Law School Admission Council (LSAC)", officialUrl: "https://www.lsac.org/lsat/about", shortDescriptionTr: "Güncel LSAT için Logical Reasoning ve Reading Comprehension hazırlığı.", shortDescriptionEn: "Logical Reasoning and Reading Comprehension preparation for the current LSAT.", displayOrder: 15, currentSpecVersion: "LSAC current at 2026-08-30", aliases: [] },
  { ...common, code: "GRE", slug: "gre", canonicalName: "GRE General Test", displayNameTr: "GRE General Test", displayNameEn: "GRE General Test", entityKind: "admission_test", customerGroup: 2, purpose: "Graduate admission test", officialBody: "Educational Testing Service (ETS)", officialUrl: "https://www.ets.org/gre/test-takers/general-test/about.html", shortDescriptionTr: "GRE General Test için Verbal, Quantitative ve Analytical Writing hazırlığı.", shortDescriptionEn: "Verbal, Quantitative and Analytical Writing preparation for the GRE General Test.", displayOrder: 16, currentSpecVersion: "GRE General Test current at 2026-08-30", aliases: [{ alias: "Graduate Record Examinations", type: "legacy", priority: 70 }, { alias: "GRE revised General Test", type: "legacy", priority: 65 }] },
  { ...common, code: "GMAT", slug: "gmat", canonicalName: "GMAT Exam", displayNameTr: "GMAT Exam", displayNameEn: "GMAT Exam", entityKind: "admission_test", customerGroup: 2, purpose: "Graduate business admission test", officialBody: "Graduate Management Admission Council (GMAC)", officialUrl: "https://www.mba.com/exams/gmat-exam", shortDescriptionTr: "GMAT Exam için Quantitative, Verbal ve Data Insights hazırlığı.", shortDescriptionEn: "Quantitative, Verbal and Data Insights preparation for the GMAT Exam.", displayOrder: 17, currentSpecVersion: "GMAT Exam current at 2026-08-30", aliases: [{ alias: "GMAT Focus Edition", type: "legacy", priority: 80 }, { alias: "Graduate Management Admission Test", type: "legacy", priority: 70 }] },
  { ...common, code: "OMPT", slug: "ompt", canonicalName: "Online Mathematics Placement Test", displayNameTr: "OMPT", displayNameEn: "OMPT", entityKind: "admission_test", customerGroup: 2, purpose: "Programme-specific mathematics placement and admission test", officialBody: "SOWISO", officialUrl: "https://www.omptest.org/", shortDescriptionTr: "Programa özgü OMPT varyantları için çevrim içi matematik hazırlığı.", shortDescriptionEn: "Online mathematics preparation for programme-specific OMPT variants.", displayOrder: 18, currentSpecVersion: "OMPT variants current at 2026-08-30", aliases: [{ alias: "Online Math Placement Test", type: "legacy", priority: 80 }, { alias: "OMPT-A", type: "variant", priority: 75 }, { alias: "OMPT-B", type: "variant", priority: 75 }, { alias: "OMPT-C", type: "variant", priority: 75 }, { alias: "OMPT-D", type: "variant", priority: 75 }, { alias: "OMPT-E", type: "variant", priority: 75 }, { alias: "OMPT-F", type: "variant", priority: 75 }] },
] satisfies readonly CanonicalExam[];

export const canonicalExamByCode = Object.fromEntries(
  canonicalExams.map((exam) => [exam.code, exam]),
) as Record<CanonicalExamCode, CanonicalExam>;
