import type { Locale } from "./dictionaries";

const copy = {
  tr: {
    eyebrow: "Sınav Hazırlığı",
    title: "Kendini Dene",
    lead: "Bir sınav seçin ve örnek değerlendirme akışını deneyin.",
    selectTitle: "Sınavınızı seçin",
    selectHint: "Tüm desteklenen sınavlarda 6 soruluk örnek test yapısı bulunur.",
    start: "Testi Başlat",
    question: "Soru",
    of: "/",
    previous: "Önceki",
    next: "Sonraki",
    finish: "Testi Bitir",
    answerPrompt: "Bir yanıt seçin",
    resultsTitle: "Sonuç Analizi",
    correct: "Doğru",
    incorrect: "Yanlış",
    accuracy: "Başarı Oranı",
    topicBreakdown: "Konu Dağılımı",
    strongAreas: "Güçlü Alanlar",
    improveAreas: "Geliştirilmesi Gereken Alanlar",
    focusAreas: "Önerilen Çalışma Alanları",
    emptyStrong: "Henüz güçlü alan oluşmadı.",
    emptyImprove: "Belirgin bir gelişim alanı yok.",
    retry: "Yeniden Dene",
    changeExam: "Başka Sınav Seç",
    notice: "Bu test yapısı örnek içerikle hazırlanmıştır. Gerçek sınav soruları ve konu dağılımları daha sonra eklenecektir.",
    performance: {
      strong: "Güçlü bir örnek performans. Nihai içerikte bu alanlarda seviyenizi koruyacak hedefli tekrar yapın.",
      moderate: "Orta düzey bir örnek performans. Düşük puanlı alanlarda hedefli pratik yapın.",
      foundation: "Temel tekrar önerilir. Önce geliştirilecek alanları gözden geçirin.",
    },
    topicPerformance: { strong: "Güçlü alan; seviyeyi koruyacak tekrar yapın.", moderate: "Hedefli soru pratiği yapın.", review: "Temel kavramları gözden geçirin." },
  },
  en: {
    eyebrow: "Exam Preparation",
    title: "Test Yourself",
    lead: "Choose an exam and experience the sample assessment flow.",
    selectTitle: "Choose your exam",
    selectHint: "Every supported exam has a six-question placeholder assessment shell.",
    start: "Start Test",
    question: "Question",
    of: "of",
    previous: "Previous",
    next: "Next",
    finish: "Finish Test",
    answerPrompt: "Choose an answer",
    resultsTitle: "Result Analysis",
    correct: "Correct",
    incorrect: "Incorrect",
    accuracy: "Accuracy",
    topicBreakdown: "Topic Breakdown",
    strongAreas: "Strong Areas",
    improveAreas: "Areas to Improve",
    focusAreas: "Recommended Focus Areas",
    emptyStrong: "No strong area has emerged yet.",
    emptyImprove: "No clear improvement area.",
    retry: "Try Again",
    changeExam: "Choose Another Exam",
    notice: "This assessment currently uses placeholder content. Final exam questions and topic distributions will be added later.",
    performance: {
      strong: "Strong sample performance. In the final assessment, use targeted review to maintain these areas.",
      moderate: "Moderate sample performance. Use targeted practice in the lower-scoring areas.",
      foundation: "Foundation review is recommended. Begin with the areas identified for improvement.",
    },
    topicPerformance: { strong: "Strong area; use review to maintain it.", moderate: "Use targeted question practice.", review: "Review the foundational concepts." },
  },
} as const;

export function getExamTestCopy(locale: Locale) { return copy[locale] || copy.tr; }
