import type { Locale } from "./dictionaries";

const copy = {
  tr: {
    eyebrow: "Sınav Hazırlığı",
    title: "Kendini Dene",
    lead: "Hedeflediğiniz sınavı seçin, 6 soruluk mini değerlendirmeyi tamamlayın ve detaylı konu analizinizi anında görün.",
    selectTitle: "Sınavınızı seçin",
    selectHint: "Tüm desteklenen sınavlarda 6 soruluk örnek değerlendirme testi bulunur.",
    start: "Testi Başlat",
    question: "Soru",
    of: "/",
    previous: "Önceki",
    next: "Sonraki",
    finish: "Testi Bitir",
    answerPrompt: "Lütfen bir yanıt seçin",
    resultsTitle: "Sonuç Analizi",
    correct: "Doğru",
    incorrect: "Yanlış",
    accuracy: "Başarı Oranı",
    questionBreakdown: "Soru Analizi",
    topicBreakdown: "Konu Performansı",
    strongAreas: "Güçlü Alanlar",
    improveAreas: "Geliştirilmesi Gereken Alanlar",
    focusAreas: "Önerilen Çalışma Alanları",
    emptyStrong: "Henüz güçlü alan oluşmadı.",
    emptyImprove: "Belirgin bir gelişim alanı yok.",
    yourAnswer: "Verdiğiniz Cevap",
    correctAnswer: "Doğru Cevap",
    explanation: "Explanation & Solution",
    nextStep: "Bir Sonraki Adım",
    nextStepBody: "Oriens Academy eğitmenleriyle sonuçlarınızı birlikte değerlendirerek hedefinize özel birebir çalışma planı oluşturabilirsiniz.",
    requestConsultation: "Ücretsiz Ön Görüşme Talep Et",
    sendToConsultant: "Sonuçlarımı Danışmana Gönder",
    sending: "Gönderiliyor...",
    sentSuccess: "Sonuçlarınız Oriens danışmanına başarıyla iletildi. En kısa sürede sizinle iletişime geçeceğiz.",
    sendModalTitle: "Sonuçlarınızı Danışmana İletin",
    sendModalDesc: "Uzman eğitmenlerimiz sınav sonuçlarınızı inceleyerek size özel çalışma stratejisi hazırlasın.",
    fullName: "Ad Soyad",
    email: "E-posta Adresi",
    phone: "Telefon Numarası",
    phonePlaceholder: "",
    sendBtn: "Sonuçları Danışmana İlet",
    cancelBtn: "Vazgeç",
    statusStrong: "Güçlü",
    statusModerate: "Geliştirilebilir",
    statusImprove: "Öncelikli Çalışma Alanı",
    retry: "Yeniden Dene",
    changeExam: "Başka Sınav Seç",
    notice: "Bu değerlendirme, seviyenizi ve konu bazlı dağılımınızı ölçmek üzere örnek akademik sorularla kurgulanmıştır.",
    emailReportCTA: "Detaylı Analizi E-postama Gönder",
    emailReportModalTitle: "Detaylı Sınav Analizini E-postanıza Alın",
    emailReportModalDesc: "Soru çözümleri, konu bazlı başarı analizi ve size özel akademik önerilerimizi e-posta kutunuza iletelim.",
    emailReportSentTitle: "Analiziniz E-postanıza Gönderildi!",
    emailReportSentDesc: "Ayrıntılı sınav çözüm raporunuz başarıyla gönderildi.",
    conversionTitle: "Sonuçlarınızı hesabınızda saklamak ister misiniz?",
    conversionDesc: "Ücretsiz Oriens hesabınızı oluşturarak: \n• Sınav geçmişinizi saklayabilir,\n• Sonuçlarınızı daha sonra tekrar inceleyebilir,\n• Randevularınızı takip edebilir,\n• Ders, paket ve ödeme bilgilerinizi tek yerden yönetebilirsiniz.",
    createAccountBtn: "Hesabımı Oluştur",
    notNowBtn: "Şimdi Değil",
    sendToMyEmail: "Sonucu E-postama Gönder",
    savingAttempt: "Sınav geçmişinize kaydediliyor...",
    attemptSaved: "Sonuç sınav geçmişinize kaydedildi.",
    attemptSaveFailed: "Sonucunuz görüntüleniyor ancak geçmişe kaydedilemedi. Tekrar deneyebilirsiniz.",
    previousQuestion: "Önceki Soru",
    nextQuestion: "Sıradaki Soru",
    completeReview: "Sonraki Adım",
    goToQuestion: "soruya git",
    performance: {
      strong: "Tebrikler! Güçlü bir temel gösterdiniz. Sınav stratejisi ve süre yönetimi odaklı ileri düzey çalışmalarla hedefinize hızla ulaşabilirsiniz.",
      moderate: "Temel yaklaşımınız iyi görünüyor ancak belirli konu alanlarında hedefli pratik ve soru analizi performansınızı belirgin şekilde artırabilir.",
      foundation: "Sonuçlarınız temel konuları sistematik şekilde tekrar etmenin faydalı olacağını gösteriyor. Öncelikli alanlara odaklanmanızı öneriyoruz.",
    },
    topicPerformance: {
      strong: "Güçlü alan; soru çözüm hızını koruyacak pratikler yapın.",
      moderate: "Geliştirilebilir; hedefli soru pratiği ve yöntem analizi önerilir.",
      review: "Öncelikli alan; temel kavramları ve formül uygulamalarını gözden geçirin.",
    },
  },
  en: {
    eyebrow: "Exam Preparation",
    title: "Test Yourself",
    lead: "Select your target exam, complete a 6-question mini diagnostic, and receive your detailed topic-level analysis instantly.",
    selectTitle: "Select your exam",
    selectHint: "All supported exams include a representative 6-question diagnostic test.",
    start: "Start Diagnostic",
    question: "Question",
    of: "/",
    previous: "Previous",
    next: "Next",
    finish: "Finish Test",
    answerPrompt: "Please choose an answer",
    resultsTitle: "Diagnostic Breakdown",
    correct: "Correct",
    incorrect: "Incorrect",
    accuracy: "Accuracy",
    questionBreakdown: "Question Breakdown",
    topicBreakdown: "Topic Performance",
    strongAreas: "Strong Areas",
    improveAreas: "Areas for Improvement",
    focusAreas: "Recommended Focus Areas",
    emptyStrong: "No strong topic identified yet.",
    emptyImprove: "No major gap identified.",
    yourAnswer: "Your Answer",
    correctAnswer: "Correct Answer",
    explanation: "Explanation & Solution",
    nextStep: "Next Step",
    nextStepBody: "Review your results with Oriens Academy instructors to build a personalized study roadmap tailored to your target score.",
    requestConsultation: "Request Free Consultation",
    sendToConsultant: "Send Results to Academic Advisor",
    sending: "Sending...",
    sentSuccess: "Your results have been sent to an Oriens advisor. We will get back to you shortly.",
    sendModalTitle: "Share Results with an Academic Advisor",
    sendModalDesc: "Our instructors will review your diagnostic test and create a personalized preparation strategy.",
    fullName: "Full Name",
    email: "Email Address",
    phone: "Phone Number",
    phonePlaceholder: "",
    sendBtn: "Send to Academic Advisor",
    cancelBtn: "Cancel",
    statusStrong: "Strong",
    statusModerate: "Developing",
    statusImprove: "Priority Focus",
    retry: "Retake Diagnostic",
    changeExam: "Choose Another Exam",
    notice: "This diagnostic is designed with representative questions to assess your foundational readiness and topic-level mastery.",
    emailReportCTA: "Email My Detailed Analysis",
    emailReportModalTitle: "Receive Your Detailed Exam Analysis by Email",
    emailReportModalDesc: "We'll send full question solutions, topic-by-topic breakdowns, and personalized academic recommendations to your inbox.",
    emailReportSentTitle: "Your Analysis Has Been Sent!",
    emailReportSentDesc: "Your detailed diagnostic report has been sent to your email.",
    conversionTitle: "Would you like to save your results in your account?",
    conversionDesc: "Create your free Oriens account to:\n• Save your diagnostic history,\n• Review your answers anytime,\n• Track your appointments,\n• Manage lessons, packages, and payments in one place.",
    createAccountBtn: "Create My Account",
    notNowBtn: "Not Now",
    sendToMyEmail: "Send Results to My Email",
    savingAttempt: "Saving to your exam history...",
    attemptSaved: "Result saved to your exam history.",
    attemptSaveFailed: "Your result is displayed, but could not be saved to history. You may retry.",
    previousQuestion: "Previous Question",
    nextQuestion: "Next Question",
    completeReview: "Next Step",
    goToQuestion: "Go to question",
    performance: {
      strong: "Well done! You demonstrated strong foundational mastery. Advanced practice focused on exam timing and strategy will help you reach top percentiles.",
      moderate: "You have a solid baseline. Targeted practice on specific weak topics and question review will significantly boost your score.",
      foundation: "Your diagnostic indicates that systematic review of foundational concepts is recommended. Focus on priority focus areas first.",
    },
    topicPerformance: {
      strong: "Strong topic; maintain problem-solving speed with regular practice.",
      moderate: "Developing; targeted practice and methodical review are recommended.",
      review: "Priority topic; review core concepts and formula applications.",
    },
  },
} as const;

export function getExamTestCopy(locale: Locale) {
  return copy[locale] || copy.tr;
}
