import type { Locale } from "./dictionaries";

const copy = {
  tr: {
    eyebrow: "Sınav Hazırlığı",
    title: "Kendini Dene",
    lead: "Hedeflediğiniz sınavı seçin, 6 soruluk mini değerlendirmeyi tamamlayın ve detaylı konu analizinizi anında görün.",
    selectTitle: "Sınavınızı seçin",
    selectHint: "Tüm desteklenen sınavlarda 6 soruluk örnek değerlendirme testi bulunur.",
    start: "Testi Başlat",
    question: "Soru",
    of: "/",
    previous: "Önceki",
    next: "Sonraki",
    finish: "Testi Bitir",
    answerPrompt: "Lütfen bir yanıt seçin",
    resultsTitle: "Sonuç Analizi",
    correct: "Doğru",
    incorrect: "Yanlış",
    accuracy: "Başarı Oranı",
    questionBreakdown: "Soru Analizi",
    topicBreakdown: "Konu Performansı",
    strongAreas: "Güçlü Alanlar",
    improveAreas: "Geliştirilmesi Gereken Alanlar",
    focusAreas: "Önerilen Çalışma Alanları",
    emptyStrong: "Henüz güçlü alan oluşmadı.",
    emptyImprove: "Belirgin bir gelişim alanı yok.",
    yourAnswer: "Verdiğiniz Cevap",
    correctAnswer: "Doğru Cevap",
    explanation: "Açıklama & Soru Çözümü",
    nextStep: "Bir Sonraki Adım",
    nextStepBody: "Oriens Academy eğitmenleriyle sonuçlarınızı birlikte değerlendirerek hedefinize özel birebir çalışma planı oluşturabilirsiniz.",
    requestConsultation: "Ücretsiz Ön Görüşme Talep Et",
    sendToConsultant: "Sonuçlarımı Danışmana Gönder",
    sending: "Gönderiliyor...",
    sentSuccess: "Sonuçlarınız Oriens danışmanına başarıyla iletildi. En kısa sürede sizinle iletişime geçeceğiz.",
    sendModalTitle: "Sonuçlarınızı Danışmana İletin",
    sendModalDesc: "Uzman eğitmenlerimiz sınav sonuçlarınızı inceleyerek size özel çalışma stratejisi hazırlasın.",
    fullName: "Ad Soyad",
    email: "E-posta Adresi",
    phone: "Telefon Numarası",
    phonePlaceholder: "0555 555 55 55",
    sendBtn: "Sonuçları Danışmana İlet",
    cancelBtn: "Vazgeç",
    statusStrong: "Güçlü",
    statusModerate: "Geliştirilebilir",
    statusImprove: "Öncelikli Çalışma Alanı",
    retry: "Yeniden Dene",
    changeExam: "Başka Sınav Seç",
    notice: "Bu değerlendirme, seviyenizi ve konu bazlı dağılımınızı ölçmek üzere örnek akademik sorularla kurgulanmıştır.",
    performance: {
      strong: "Tebrikler! Güçlü bir temel gösterdiniz. Sınav stratejisi ve süre yönetimi odaklı ileri düzey çalışmalarla hedefinize hızla ulaşabilirsiniz.",
      moderate: "Temel yaklaşımınız iyi görünüyor ancak belirli konu alanlarında hedefli pratik ve soru analizi performansınızı belirgin şekilde artırabilir.",
      foundation: "Sonuçlarınız temel konuları sistematik şekilde tekrar etmenin faydalı olacağını gösteriyor. Öncelikli alanlara odaklanmanızı öneriyoruz.",
    },
    topicPerformance: {
      strong: "Güçlü alan; soru çözüm hızını koruyacak pratikler yapın.",
      moderate: "Geliştirilebilir; hedefli soru pratiği ve yöntem analizi önerilir.",
      review: "Öncelikli alan; temel kavramları ve formül uygulamalarını gözden geçirin.",
    },
  },
  en: {
    eyebrow: "Exam Preparation",
    title: "Test Yourself",
    lead: "Select your target exam, complete the 6-question mini diagnostic, and receive your detailed topic analysis instantly.",
    selectTitle: "Choose your exam",
    selectHint: "Every supported exam includes a structured 6-question diagnostic assessment.",
    start: "Start Test",
    question: "Question",
    of: "of",
    previous: "Previous",
    next: "Next",
    finish: "Finish Test",
    answerPrompt: "Please choose an answer",
    resultsTitle: "Result Analysis",
    correct: "Correct",
    incorrect: "Incorrect",
    accuracy: "Accuracy",
    questionBreakdown: "Question Analysis",
    topicBreakdown: "Topic Performance",
    strongAreas: "Strong Areas",
    improveAreas: "Areas to Improve",
    focusAreas: "Recommended Focus Areas",
    emptyStrong: "No strong area has emerged yet.",
    emptyImprove: "No specific improvement area.",
    yourAnswer: "Your Answer",
    correctAnswer: "Correct Answer",
    explanation: "Solution & Explanation",
    nextStep: "Recommended Next Step",
    nextStepBody: "Discuss your results with Oriens Academy academic consultants to design a structured 1-on-1 preparation plan.",
    requestConsultation: "Request Free Consultation",
    sendToConsultant: "Send Results to Consultant",
    sending: "Sending...",
    sentSuccess: "Your results have been successfully sent to our consultant. We will reach out to you shortly.",
    sendModalTitle: "Send Your Results to an Academic Consultant",
    sendModalDesc: "Our expert tutors will analyze your diagnostic performance and prepare a personalized preparation roadmap.",
    fullName: "Full Name",
    email: "Email Address",
    phone: "Phone Number",
    phonePlaceholder: "Phone number",
    sendBtn: "Send Results to Consultant",
    cancelBtn: "Cancel",
    statusStrong: "Strong",
    statusModerate: "Moderate",
    statusImprove: "Priority Focus",
    retry: "Try Again",
    changeExam: "Choose Another Exam",
    notice: "This diagnostic is designed with representative academic questions to evaluate your topic proficiency.",
    performance: {
      strong: "Outstanding performance! You have demonstrated a solid academic foundation. Advanced time management and question drills will maximize your score.",
      moderate: "Good foundational understanding. Targeted practice and methodical problem-solving in specific topics will significantly improve your results.",
      foundation: "A systematic review of foundational concepts is recommended. Focusing on priority areas will help you build confidence rapidly.",
    },
    topicPerformance: {
      strong: "Strong topic; maintain problem-solving speed and accuracy.",
      moderate: "Moderate proficiency; targeted practice and error analysis recommended.",
      review: "Priority topic; review underlying formulas and core principles.",
    },
  },
} as const;

export function getExamTestCopy(locale: Locale) {
  return copy[locale] || copy.tr;
}
