import type { Locale } from "./dictionaries";

const paymentCopy = {
  tr: {
    eyebrow: "Güvenli Ödeme",
    title: "Paket ödemenizi tamamlayın.",
    lead: "Yalnızca çevrim içi satın almaya açılmış paketler için ödeme talebi oluşturulabilir.",
    card: "Kart ile Ödeme",
    package: "Seçilen Paket",
    noPackage: "Çevrim içi satın alınabilir bir paket seçilmedi.",
    backPricing: "Paketleri İncele",
    fullName: "Ad Soyad",
    email: "E-posta",
    phone: "Telefon (isteğe bağlı)",
    cardNumber: "Kart Numarası",
    cardHolder: "Kart Üzerindeki İsim",
    expiry: "Son Kullanma Tarihi",
    cvv: "CVV",
    continuePayment: "Ödemeye Devam Et",
    secureText: "Kartlı ödemeler banka altyapısı ve 3D Secure doğrulaması üzerinden gerçekleştirilir. Kart bilgileriniz 256-bit SSL şifreleme ile korunur ve sunucularımızda saklanmaz.",
    terms: "Gizlilik Politikası ve Kullanım Koşulları'nı okudum ve kabul ediyorum.",
    resultTitle: "Ödeme Durumu",
    verifying: "Ödeme durumu sunucudan doğrulanıyor…",
    verificationFailed: "Ödeme durumu doğrulanamadı. URL bilgileri tek başına başarılı ödeme olarak kabul edilmez.",
  },
  en: {
    eyebrow: "Secure Payment",
    title: "Complete your package payment.",
    lead: "A payment request can only be created for packages explicitly enabled for online purchase.",
    card: "Pay by Card",
    package: "Selected Package",
    noPackage: "No package enabled for online purchase has been selected.",
    backPricing: "View Packages",
    fullName: "Full Name",
    email: "Email",
    phone: "Phone (optional)",
    cardNumber: "Card Number",
    cardHolder: "Name on Card",
    expiry: "Expiry Date",
    cvv: "CVV",
    continuePayment: "Continue to Payment",
    secureText: "Card payments are processed through the bank infrastructure and 3D Secure verification. Your card details are protected with 256-bit SSL encryption and are never stored on our servers.",
    terms: "I have read and accept the Privacy Policy and Terms of Service.",
    resultTitle: "Payment Status",
    verifying: "Verifying payment status with the server…",
    verificationFailed: "Payment status could not be verified. URL values alone are never treated as proof of successful payment.",
  },
} as const;

export function getPaymentCopy(locale: Locale) { return paymentCopy[locale]; }
