import type { Locale } from "./dictionaries";

const paymentCopy = {
  tr: {
    eyebrow: "Güvenli Ödeme",
    title: "Paket ödemenizi tamamlayın.",
    lead: "Yalnızca çevrim içi satın almaya açılmış paketler için ödeme talebi oluşturulabilir.",
    card: "Kart ile Ödeme",
    transfer: "Banka Havalesi / EFT",
    package: "Seçilen Paket",
    noPackage: "Çevrim içi satın alınabilir bir paket seçilmedi.",
    backPricing: "Paketleri İncele",
    fullName: "Ad Soyad",
    email: "E-posta",
    phone: "Telefon (isteğe bağlı)",
    cardNumber: "Kart Numarası",
    cardHolder: "Kart Üzerindeki İsim",
    expiry: "Son Kullanma Tarihi",
    cvv: "CVV",
    hostedField: "Bankanın güvenli ödeme sayfasında girilir",
    continuePayment: "Ödemeye Devam Et",
    cardPending: "Kartlı ödeme, resmî banka Virtual POS bilgileri ve sandbox erişimi tamamlandıktan sonra etkinleştirilecektir.",
    secureText: "Kartlı ödeme etkinleştirildiğinde, desteklenen işlemler bankanın güvenli ödeme altyapısı ve 3D Secure doğrulaması üzerinden gerçekleştirilir.",
    accountHolder: "Hesap Sahibi",
    bank: "Banka",
    iban: "IBAN",
    copyIban: "IBAN'ı Kopyala",
    copyAccount: "Hesap Bilgisini Kopyala",
    copied: "IBAN kopyalandı.",
    accountCopied: "Hesap bilgisi kopyalandı.",
    transferMissing: "Banka havalesi bilgileri henüz yapılandırılmadı.",
    createTransfer: "Havale Talebi Oluştur",
    referenceNotice: "Açıklama alanında oluşturulan ödeme referansını kullanın. Havale, yönetici onayından sonra işlenir.",
    terms: "Gizlilik Politikası ve Kullanım Koşulları'nı okudum ve kabul ediyorum.",
    resultTitle: "Ödeme Durumu",
    verifying: "Ödeme durumu sunucudan doğrulanıyor…",
    verificationFailed: "Ödeme durumu doğrulanamadı. URL bilgileri tek başına başarılı ödeme olarak kabul edilmez.",
  },
  en: {
    eyebrow: "Secure Payment",
    title: "Complete your package payment.",
    lead: "A payment request can only be created for packages explicitly enabled for online purchase.",
    card: "Pay by Card",
    transfer: "Bank Transfer",
    package: "Selected Package",
    noPackage: "No package enabled for online purchase has been selected.",
    backPricing: "View Packages",
    fullName: "Full Name",
    email: "Email",
    phone: "Phone (optional)",
    cardNumber: "Card Number",
    cardHolder: "Name on Card",
    expiry: "Expiry Date",
    cvv: "CVV",
    hostedField: "Entered on the bank's secure hosted payment page",
    continuePayment: "Continue to Payment",
    cardPending: "Card payments will be enabled after official bank Virtual POS documentation and sandbox access are supplied.",
    secureText: "Once card payment is enabled, eligible transactions use the bank's secure payment infrastructure and 3D Secure authentication.",
    accountHolder: "Account Holder",
    bank: "Bank",
    iban: "IBAN",
    copyIban: "Copy IBAN",
    copyAccount: "Copy Account Details",
    copied: "IBAN copied.",
    accountCopied: "Account details copied.",
    transferMissing: "Bank transfer details have not been configured yet.",
    createTransfer: "Create Transfer Request",
    referenceNotice: "Use the generated payment reference in the transfer description. Transfers are processed after administrative review.",
    terms: "I have read and accept the Privacy Policy and Terms of Service.",
    resultTitle: "Payment Status",
    verifying: "Verifying payment status with the server…",
    verificationFailed: "Payment status could not be verified. URL values alone are never treated as proof of successful payment.",
  },
} as const;

export function getPaymentCopy(locale: Locale) { return paymentCopy[locale]; }
