import type { Locale } from "./dictionaries";

const copy = {
  tr: {
    action: "İade İşlemi",
    title: "Ödeme İadesi",
    fullRefund: "Tam İade",
    partialRefund: "Kısmi İade",
    remainingRefund: "Kalan Dersleri İade Et",
    paidAmount: "Ödenen Tutar",
    refundedAmount: "Daha Önce İade Edilen",
    refundableAmount: "İade Edilebilir Tutar",
    refundAmount: "İade Tutarı",
    refundReason: "İade Nedeni",
    lessonsToRevoke: "İade Edilecek Ders Hakkı",
    completedLessons: "Tamamlanan / Kullanılan",
    remainingLessons: "Kalan Kullanılabilir",
    success: "İade başarıyla tamamlandı.",
    failed: "İade işlemi tamamlanamadı.",
    paid: "Ödendi",
    partiallyRefunded: "Kısmen İade Edildi",
    refunded: "İade Edildi",
    cancel: "Vazgeç",
    continue: "İadeyi İncele",
  },
  en: {
    action: "Refund Action",
    title: "Payment Refund",
    fullRefund: "Full Refund",
    partialRefund: "Partial Refund",
    remainingRefund: "Refund Remaining Lessons",
    paidAmount: "Paid Amount",
    refundedAmount: "Previously Refunded",
    refundableAmount: "Refundable Amount",
    refundAmount: "Refund Amount",
    refundReason: "Refund Reason",
    lessonsToRevoke: "Lesson Rights to Revoke",
    completedLessons: "Completed / Used",
    remainingLessons: "Remaining Unused",
    success: "Refund completed successfully.",
    failed: "Refund could not be completed.",
    paid: "Paid",
    partiallyRefunded: "Partially Refunded",
    refunded: "Refunded",
    cancel: "Cancel",
    continue: "Review Refund",
  },
} as const;

export function getPaymentRefundCopy(locale: Locale) { return copy[locale]; }
