import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { sanitizeAuditValue } from "../src/lib/audit/sanitize";
import { canonicalDateToDisplay, displayDateToCanonical } from "../src/components/admin/ControlledLessonDateTime";

const root=process.cwd(); const read=(path:string)=>readFileSync(resolve(root,path),"utf8");
const migration=read("supabase/migrations/20260916090000_customer_revisions_v2.sql");
const manager=read("src/components/admin/StudentLearningManager.tsx");
const profile=read("src/components/admin/StudentDetailSheet.tsx");
const outbox=read("supabase/functions/process-notification-outbox/index.ts");
const trHome=read("src/content/tr/home.ts"); const enHome=read("src/content/en/home.ts");
const trAbout=read("src/content/tr/about.ts"); const enAbout=read("src/content/en/about.ts");

const tests:Array<[string,()=>void]> = [
  ["audit uses one stream and controlled schema",()=>{assert.match(migration,/alter table public\.audit_logs/);assert.doesNotMatch(migration,/create table[^;]*error/i);for(const value of ["info","warning","error","critical","auth","database","edge"])assert.ok(migration.includes(`'${value}'`));}],
  ["sanitizer recursively redacts secrets",()=>{const safe=sanitizeAuditValue({message:"bounded",password:"x",nested:{authorization:"Bearer x",token:"x",secret:"x",cookie:"x",pan:"4111111111111111",cvv:"123"}});const json=JSON.stringify(safe);for(const secret of ["Bearer x","4111111111111111","123","\"x\""])assert.ok(!json.includes(secret),json);assert.ok(json.includes("[REDACTED]"));}],
  ["academic layout and fields",()=>{for(const label of ["Eğitim Programı","Aldığı Sınavlar"])assert.ok(profile.includes(label));/* referans admin detayında hedef ülke/üniversite yok */assert.ok(!profile.includes("Hedef Ülke")&&!profile.includes("Hedef Üniversite"));assert.ok(!profile.includes('label="Hedef Sınavlar"'));assert.match(migration,/education_program text/);assert.match(migration,/exams_taken text\[\]/);}],
  ["topic seed and no instructor seed",()=>{for(const [index,label] of ["IB Math HL","IB Physics HL","SAT Math","ESAT Math","ESAT Physics"].entries())assert.ok(migration.includes(`('${label}',${index+1})`));const setup=migration.slice(migration.indexOf("create table if not exists public.instructors"),migration.indexOf("create or replace function public.admin_manage_lesson_reference"));assert.doesNotMatch(setup,/insert into public\.instructors\s*\(/i);assert.match(migration,/LESSON_REFERENCE_DELETE_FORBIDDEN/);}],
  ["deterministic date conversion",()=>{/* görünen biçim GG.AA.YYYY */assert.equal(canonicalDateToDisplay("2026-09-16"),"16.09.2026");assert.equal(displayDateToCanonical("16.09.2026"),"2026-09-16");assert.equal(displayDateToCanonical("31.02.2026"),null);assert.ok(manager.includes("ControlledLessonTime"));assert.ok(!manager.includes('type="datetime-local"'));}],
  ["lesson form derives title and has optional email",()=>{assert.ok(!manager.includes("Ders Başlığı"));assert.match(manager,/const selectedCourse = topics\.find\(\(item\) => item\.id === pastForm\.topicId\);\s*const title = /);assert.match(manager,/E-posta gönder/);assert.match(manager,/sendEmail: false/);}],
  ["completed edit preserves ledger count",()=>{assert.match(migration,/admin_update_completed_lesson/);assert.match(migration,/lesson_delta<>-1/);assert.match(migration,/count\(\*\).*linked_lesson_id=p_lesson_id/);const body=migration.slice(migration.indexOf("admin_update_completed_lesson"));assert.doesNotMatch(body,/insert into public\.student_package_adjustments/);assert.match(body,/lesson\.package_changed/);}],
  ["MAIL-044 durable idempotent outbox",()=>{assert.match(migration,/past_lesson_confirmation_manual:'\|\|v_lesson\.id/);assert.match(outbox,/row\.template === "past_lesson_confirmation_manual"/);assert.ok(!outbox.includes("Geçmiş Ders Kaydınız Oluşturuldu | Oriens Academy"));}],
  ["MAIL-009, 042, 043 clean structured subjects",()=>{/* MAIL-009 konusu paylaşılan payment-success.ts şablonunda */assert.ok(read("supabase/functions/_shared/email/payment-success.ts").includes("Ödemeniz Başarıyla Alındı ve Ders Paketiniz Tanımlandı"));assert.match(outbox,/renderPaymentSuccessEmail\("guardian"/);for(const value of ["Ders Hakkınız Güncellendi","Güncel Ders Haklarınız"])assert.ok(outbox.includes(value));assert.doesNotMatch(outbox,/\| Oriens Academy/);assert.match(outbox,/table role="presentation"/);}],
  ["content exact and school parity",()=>{assert.ok(trHome.includes("Calculus, Lineer Cebir, Diferansiyel Denklemler, Fizik I-II, İstatistik, Kimya ve Biyoloji gibi çeşitli alanlarda ders takviyesi."));assert.ok(enHome.includes("Course support across a range of subjects, including Calculus, Linear Algebra, Differential Equations, Physics I-II, Statistics, Chemistry and Biology."));for(const school of ["Robert Kolej","Galatasaray Lisesi","Üsküdar Amerikan Lisesi","İstanbul Alman Lisesi","St. Joseph Fransız Lisesi","Notre Dame de Sion Fransız Lisesi","İzmir Amerikan Koleji","Tarsus Amerikan Koleji","St. Georg Avusturya Lisesi"])assert.ok(trAbout.includes(school));for(const school of ["Robert College","Galatasaray High School","Üsküdar American Academy","Deutsche Schule Istanbul","St. Joseph French High School","Notre Dame de Sion French High School","İzmir American Collegiate Institute","Tarsus American College","St. Georg Austrian High School"])assert.ok(enAbout.includes(school));}],
];
let passed=0;for(const [name,test] of tests){test();passed++;console.log(`PASS ${name}`);}console.log(`${passed}/${tests.length} customer revision V2 checks passed`);
