"use client";

import { useEffect, useRef, useState, type FormEvent } from "react";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { AccountWaveLoader } from "@/components/auth/AccountWaveLoader";
import { useLocale } from "@/content/locale-context";
import { useAccount } from "@/lib/auth/account-context";
import { destinationForAccount, loginPathWithReturn } from "@/lib/auth/account-routing";
import { changePasswordPath } from "@/lib/routes";
import { getSupabaseClient } from "@/lib/supabase/client";

function strong(value:string){return value.length>=8&&/[a-z]/.test(value)&&/[A-Z]/.test(value)&&/[0-9]/.test(value)&&/[^A-Za-z0-9]/.test(value);}
export function AccountPasswordChangePage(){const locale=useLocale();const router=useRouter();const{accountType,user,isInitializing,refreshAccount}=useAccount();const[password,setPassword]=useState("");const[confirm,setConfirm]=useState("");const[pending,setPending]=useState(false);const[error,setError]=useState("");const navigated=useRef(false);
  useEffect(()=>{if(isInitializing||navigated.current)return;if(accountType==="unauthenticated"||accountType==="unknown"){navigated.current=true;router.replace(loginPathWithReturn(locale,changePasswordPath(locale)));return;}if(user?.user_metadata?.force_password_change!==true){navigated.current=true;router.replace(destinationForAccount(accountType,locale));}},[accountType,isInitializing,locale,router,user]);
  async function submit(event:FormEvent){event.preventDefault();if(pending)return;if(!strong(password)){setError(locale==="tr"?"Şifre en az 8 karakter olmalı; büyük harf, küçük harf, sayı ve sembol içermelidir.":"Use at least 8 characters with uppercase, lowercase, a number and a symbol.");return;}if(password!==confirm){setError(locale==="tr"?"Şifreler eşleşmiyor.":"Passwords do not match.");return;}setPending(true);setError("");const supabase=getSupabaseClient();const{error:updateError}=await supabase.auth.updateUser({password,data:{force_password_change:false}});if(updateError){setPending(false);setError(locale==="tr"?"Şifre güncellenemedi.":"Password could not be updated.");return;}if(accountType==="admin"&&user?.id)await supabase.from("audit_logs").insert({actor_user_id:user.id,action:"admin.password_change_completed",entity_type:"admin_auth",entity_id:user.id,metadata:{trigger:"forced_recovery_change"}});await refreshAccount();navigated.current=true;router.replace(destinationForAccount(accountType,locale));}
  if(isInitializing||pending||!["admin","student"].includes(accountType)||user?.user_metadata?.force_password_change!==true)return <AccountWaveLoader/>;
  return <section className="min-h-screen bg-background px-4 pt-28 pb-16 sm:pt-32"><div className="mx-auto w-full max-w-md"><div className="mb-6 flex justify-center"><Image src="/brand/oriens-logo-v2.png" alt="Oriens Academy" width={217} height={80} className="h-14 w-auto" priority/></div><div className="rounded-3xl border border-border bg-surface p-5 shadow-editorial sm:p-8"><h1 className="text-center font-heading text-3xl text-ink">{locale==="tr"?"Yeni Şifre Belirleyin":"Set a New Password"}</h1><p className="mt-2 text-center text-sm leading-6 text-muted-foreground">{locale==="tr"?"Devam etmeden önce hesabınız için yeni bir şifre oluşturun.":"Create a new password for your account before continuing."}</p>{error&&<div role="alert" className="mt-5 rounded-xl border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}<form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-xs font-semibold">{locale==="tr"?"Yeni Şifre":"New Password"}<input type="password" autoComplete="new-password" value={password} onChange={(event)=>setPassword(event.target.value)} className="mt-1.5 min-h-12 w-full rounded-xl border border-input bg-background px-3 text-sm"/></label><label className="block text-xs font-semibold">{locale==="tr"?"Yeni Şifre (Tekrar)":"Confirm New Password"}<input type="password" autoComplete="new-password" value={confirm} onChange={(event)=>setConfirm(event.target.value)} className="mt-1.5 min-h-12 w-full rounded-xl border border-input bg-background px-3 text-sm"/></label><button disabled={!password||!confirm} className="min-h-12 w-full rounded-xl bg-ink px-5 text-sm font-semibold text-white disabled:opacity-45">{locale==="tr"?"Şifreyi Güncelle":"Update Password"}</button></form></div></div></section>;}
